(ns paginae.common.activity-card
  {:no-dynamic true}
  (:require
   ["package:cljd_paginae/l10n/app_localizations.dart" :as app-l10n]
   ["package:flutter/material.dart" :as material]
   ["package:intl/intl.dart" :as intl]
   ["package:material_symbols_icons/symbols.dart" :as symbols]
   ["package:share_plus/share_plus.dart" :as share_plus]
   [cljd.flutter :as flutter]
   [paginae.common.image.widget :as image]
   [paginae.types.activity :as activity-type]))

(defn activity-card
  "Card for displaying a reading activity.
   Pass :on-edit and/or :on-delete in the options map
   to show an actions row."
  [{:keys [data
           with-cover?
           on-edit
           on-delete]}]
  (flutter/widget
   :get {{{:flds [bodyLarge titleMedium labelLarge labelMedium]} .-textTheme
          {:flds [onSurface]} .-colorScheme} material/Theme}
   :context context
   :let [locale (material/Localizations.localeOf context)
         locales (app-l10n/AppLocalizations.of context)
         book (:book data)
         activity (:activity data)]

   (material/Card)

   .child
   (material/Padding
    .padding (material/EdgeInsets.all 5))

   .child
   (material/ConstrainedBox
    .constraints
    (material/BoxConstraints .minHeight 80))

   .child
   (material/Row
    .spacing 10)

   .children
   [;; Cover image
    (flutter/widget
     :when with-cover?

     (image/cover-image
      {:book book
       :placeholder-text (.-noCover locales)
       :bordered? false
       :clickable? false
       :on-click nil
       :width 100}))

    (material/Expanded

     .child
     (material/Column
      .crossAxisAlignment
      (if with-cover?
        material/CrossAxisAlignment.start
        material/CrossAxisAlignment.center)

      .children
      [;; Read date
       (material/Text
        (str
         (.format
          (intl/DateFormat.yMMMd (.toString locale))
          (:date activity))
         " "
         (.format
          (intl/DateFormat.Hm (.toString locale))
          (:date activity)))

        .textAlign
        (if with-cover?
          material/TextAlign.start
          material/TextAlign.center)

        .style
        (.copyWith
         labelLarge

         .color
         (.withOpacity onSurface 0.7)))

       (material/SizedBox
        .height
        (if with-cover?
          20
          10))

       ;; Title
       (flutter/widget
        :when with-cover?

        (material/Text
         (:title book)

         .style
         titleMedium))

       ;; Activity
       (material/Text
        (activity-type/activity-string (:activity data) (:book data) locales)

        .textAlign
        (if with-cover?
          material/TextAlign.start
          material/TextAlign.center)

        .softWrap
        true

        .style
        bodyLarge)

       ;; Actions
       (flutter/widget
        :when (or on-edit on-delete)

        (material/Row
         .mainAxisAlignment material/MainAxisAlignment.center

         .children
         [      ;; Share button
          (material/TextButton

           .child
           (material/Row
            .spacing 5

            .children
            [(material/Icon
              symbols/Symbols.share

              .color
              onSurface)

             (material/Text
              (.toUpperCase (.-share locales))

              .style
              labelMedium)])

           .onPressed
           (fn []
             (let [date (.format
                         (intl/DateFormat.yMMMMd (.toString locale))
                         (:date activity))]
               (.share share_plus/SharePlus.instance
                       (share_plus/ShareParams.
                        .text
                        (if (:pages book)
                          (str "On " date ", I reached page " (.round (* (:pages book) (:progress activity))) " of \"" (:title book) "\"")
                          (str "On " date ", I reached "  (* 100 (:progress activity)) " of the way through \"" (:title book) "\"")
                          )

                        ;; (.shareActivityTest locales book-name (:contents note))
                        )))
             nil))

          (when on-edit
            (material/TextButton

             .child
             (material/Row
              .spacing 5

              .children
              [(material/Icon
                symbols/Symbols.edit

                .color
                onSurface)

               (material/Text
                (.toUpperCase (.-edit locales))

                .style
                labelMedium)])

             .onPressed on-edit))

          (when on-delete
            (material/TextButton

             .child
             (material/Row
              .spacing 5

              .children
              [(material/Icon
                symbols/Symbols.delete

                .color
                material/Colors.red)

               (material/Text
                (.toUpperCase (.-delete locales))

                .style
                (.copyWith
                 labelMedium

                 .color
                 material/Colors.red))])

             .onPressed on-delete))]))]))]))