(ns paginae.common.badges
  {:no-dynamic true}
  (:require
   ["package:flutter/material.dart" :as material]
   ["package:material_symbols_icons/symbols.dart" :as symbols]
   [paginae.theme :as theme]
   [cljd.flutter :as flutter]))

(defn- badge-widget
  "Book status badge"
  [{:keys [bg-color
           icon
           color
           fill]}]
  (flutter/widget
   (material/Container
    .decoration
    (material/BoxDecoration
     .color
     bg-color

     .borderRadius
     (material/BorderRadiusGeometry.circular 10)))

   .child
   (material/Padding
    .padding
    (material/EdgeInsets.all 20))

   .child
   (material/Icon
    icon

    .fill
    fill

    .color
    color

    .fontWeight
    material/FontWeight.bold)))

(defn badge
  "Widget that shows a badge according to a book's status"
  [status]
  (let [data (case status
               :done {:icon symbols/Symbols.check_circle
                      :color (:10 theme/primary)
                      :bg-color (:70 theme/primary)
                      :fill 0.0}

               :reading {:icon symbols/Symbols.book_ribbon
                         :color (:10 theme/neutral)
                         :bg-color (:70 theme/neutral)
                         :fill 0.0}

               :favorite {:icon symbols/Symbols.favorite
                          :color (:10 theme/tertiary)
                          :bg-color (:70 theme/tertiary)
                          :fill 1.0}

               ;; to-read as default
               {:icon symbols/Symbols.bookmark
                :color (:10 theme/secondary)
                :bg-color (:70 theme/secondary)
                :fill 1.0})]

    (badge-widget data)))
