name: cljd_paginae
description: "App to track reading"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # HTTP requests
  http: ^1.1.2

  # Barcode reader
  mobile_scanner: ^7.2.0

  # Material symbols
  material_symbols_icons: ^4.2928.1

  # String localizations
  flutter_localizations:
    sdk: flutter
  intl: any

  # Dotted border
  dotted_border: ^3.1.0

  # Image picker
  image_picker: ^1.2.1
  
  # Path provider
  path_provider: ^2.1.5

  # uuid
  uuid: ^4.5.3

  # sqlite
  sqflite: ^2.4.2+1

  # path
  path: ^1.9.1

  # image
  image: ^4.8.0

  # carousel
  carousel_slider: ^5.1.2

  # share
  share_plus: ^13.3.0

  # calendar
  table_calendar: ^3.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  generate: true

  uses-material-design: true

  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope-VariableFont_wght.ttf
          weight: 200
        - asset: assets/fonts/Manrope-VariableFont_wght.ttf
          weight: 400
        - asset: assets/fonts/Manrope-VariableFont_wght.ttf
          weight: 600
        - asset: assets/fonts/Manrope-VariableFont_wght.ttf
          weight: 800

    - family: NotoSerif
      fonts:
        - asset: assets/fonts/NotoSerif-VariableFont_wdth,wght.ttf
        - asset: assets/fonts/NotoSerif-Italic-VariableFont_wdth,wght.ttf
          style: italic

  assets:
    - assets/images/book-cover.png
    - assets/sql/schema.sql
