(ns paginae.home.home
  (:require [cljd.flutter :as flutter]
            ["package:flutter/material.dart" :as material]
            ["package:flutter/widgets.dart" :as widgets]
            [paginae.database :as db]
            [paginae.image.widget :as image]
            [paginae.home.badges :as badges]
            ["../l10n/app_localizations.dart" :as app-l10n]
            [paginae.theme :as theme]))

(defn- reading-book-card
  "Card to display currently reading book"
  [book]

  (flutter/widget
   :get {{{:flds [titleLarge bodyMedium]} .-textTheme} material/Theme}
   :context context
   :let [locales (app-l10n/AppLocalizations.of context)]

   (material/Card

    .child
    (material/Container

     .padding
     (material/EdgeInsets.all 10)

     .child
     (material/Column
      .crossAxisAlignment material/CrossAxisAlignment.start

      .children
      [(image/cover-image
        {:book book
         :placeholder-text (.-noCover locales)
         :bordered? false
         :clickable? false
         :on-click nil
         :width 175})

       (material/Text
        (:title book)

        .style
        (.copyWith titleLarge
                   .fontWeight material/FontWeight.bold)

        .overflow material/TextOverflow.ellipsis)

       (material/Text
        (:author book)

        .style bodyMedium

        .overflow material/TextOverflow.ellipsis)

       (material/Expanded

        .child
        (material/Row

         .mainAxisAlignment material/MainAxisAlignment.spaceBetween

         .children
         [(material/Text (.toUpperCase "68% complete"))
          (material/Text (.toUpperCase "page 192"))])) ;; TODO: Change to actual progress

       (material/LinearProgressIndicator
        .value 0.68)])))))

(defn- books-reading
  "Widget to display currently reading books"
  [{:keys [go-to-add]}]

  (flutter/widget
   :get {{{:flds [bodyMedium headlineSmall titleLarge titleMedium]} .-textTheme
          {:flds [primary onPrimary]} .-colorScheme} material/Theme}
   :context context
   :let [locales (app-l10n/AppLocalizations.of context)]

   (material/SliverToBoxAdapter
    .child

    (material/Center
     .child

     (material/FutureBuilder
      .future
      (db/get-books-by-status :reading)

      .builder
      (fn [_context ^widgets/AsyncSnapshot snapshot]
        (if (.-hasData snapshot)
          (let [books (.-data snapshot)]

            (if (empty? books)
              (material/Column

               .spacing 10

               .children
               [(material/Text
                 (.-noBooks locales)

                 .style (.copyWith titleLarge
                                   .fontFamily "Manrope"))

                (material/FilledButton

                 .onPressed go-to-add

                 .child
                 (material/Text
                  (.toUpperCase (.-addNewBook locales))

                  .style (.copyWith titleMedium
                                    .color onPrimary
                                    .fontFamily "Manrope"
                                    .fontWeight material/FontWeight.bold)))])

              (material/Column

               .spacing 10

               .children
               [(material/Row
                 .mainAxisAlignment material/MainAxisAlignment.spaceBetween

                 .children
                 [;; Section title
                  (material/Text
                   (.-currentlyReading locales)
                   .softWrap true
                   .maxLines 2
                   .style headlineSmall)

                  ;; Book count 
                  (material/Text
                   (.toUpperCase ^String ((.-booksInProgress locales) (count books)))
                   .softWrap true
                   .maxLines 2
                   .style (.copyWith bodyMedium
                                     .fontWeight material/FontWeight.bold
                                     .color primary))])

                (material/SizedBox
                 .height 400

                 .child
                 (material/PageView.builder
                  .itemCount
                  (count books)

                  .itemBuilder
                  (fn [_context idx]
                    (let [book (nth books idx)]
                      (material/Padding
                       .padding

                       (material/EdgeInsets.symmetric
                        .horizontal 4)

                       .child
                       (reading-book-card book))))))])))

          (material/CircularProgressIndicator))))))))

(defn- shelf-card
  "Card that represents a 'bookshelf' (group of books)"
  [{:keys [title subtitle bg-color number badge on-tap]}]
  (flutter/widget
   :get {{{:flds [headlineLarge titleLarge labelMedium]} .-textTheme
          {:flds [onSurfaceVariant]} .-colorScheme} material/Theme}

   (material/InkWell
    .onTap on-tap

    .child
    (material/Card

     .child
     (material/Padding

      .padding
      (material/EdgeInsets.symmetric .vertical 20 .horizontal 20)

      .child
      (material/Column

       .crossAxisAlignment material/CrossAxisAlignment.start

       .children
       [;; Icon and count
        (material/Row

         .mainAxisAlignment
         material/MainAxisAlignment.spaceBetween

         .children
         [;; Icon
          badge

          ;; Count
          (material/Text
           (str number)

           .style
           (.copyWith headlineLarge
                      .fontWeight material/FontWeight.w700
                      .color bg-color))])

        (material/SizedBox
         .height 20)

        ;; Title
        (material/Text
         title

         .style titleLarge)

        ;; Subtitle
        (material/Text
         (.toUpperCase ^String subtitle)

         .style (.copyWith labelMedium
                           .color (.withOpacity onSurfaceVariant 0.75)))]))))))

(defn- shelves
  "Widget that contains cards with book groups"
  [{:keys [go-to-to-read-shelf
           go-to-reading-shelf
           go-to-favorite-shelf
           go-to-done-shelf]}]
  (flutter/widget
   :get {{{:flds [headlineSmall]} .-textTheme} material/Theme}
   :context context
   :let [locales (app-l10n/AppLocalizations.of context)
         portrait? (= material/Orientation.portrait (.-orientation (material/MediaQuery.of context)))]

   (material/FutureBuilder
    .future
    (db/get-book-counts)

    .builder
    (fn [_context ^widgets/AsyncSnapshot snapshot]
      (if (.-hasData snapshot)
        (let [counts (.-data snapshot)]
          (material/SliverMainAxisGroup

           .slivers
           [(material/SliverToBoxAdapter

             .child
             (material/Text
              (.-myShelves locales)
              .softWrap true
              .maxLines 2
              .style headlineSmall))

            (material/SliverGrid.count
             .crossAxisCount (if portrait? 2 4)

             .children
             [(shelf-card {:title (.-shelfReadTitle locales)
                           :subtitle (.-shelfReadSubtitle locales)
                           :bg-color (:70 theme/primary)
                           :number (:done counts)
                           :badge (badges/read-badge)
                           :on-tap go-to-done-shelf})

              (shelf-card {:title (.-shelfToReadTitle locales)
                           :subtitle (.-shelfToReadSubtitle locales)
                           :bg-color (:70 theme/secondary)
                           :number (:to-read counts)
                           :badge (badges/to-read-badge)
                           :on-tap go-to-to-read-shelf})

              (shelf-card {:title (.-shelfFavoritesTitle locales)
                           :subtitle (.-shelfFavoritesSubtitle locales)
                           :bg-color (:70 theme/tertiary)
                           :number (:favorite counts)
                           :badge (badges/favorite-badge)
                           :on-tap go-to-favorite-shelf})

              (shelf-card {:title (.-shelfReadingTitle locales)
                           :subtitle (.-shelfReadingSubtitle locales)
                           :bg-color (:70 theme/neutral)
                           :number (:reading counts)
                           :badge (badges/reading-badge)
                           :on-tap go-to-reading-shelf})])]))

        (material/SliverToBoxAdapter
         .child
         (material/CircularProgressIndicator)))))))

(defn- recent-activity
  [{:keys [go-to-journal]}]
  (flutter/widget
   :get {{{:flds [headlineSmall labelLarge]} .-textTheme
          {:flds [secondary]} .-colorScheme} material/Theme}
   :context context
   :let [locales (app-l10n/AppLocalizations.of context)]

   (material/FutureBuilder
    .future
    (db/get-recent-activity 5)

    .builder
    (fn [_context ^widgets/AsyncSnapshot snapshot]
      (if (.-hasData snapshot)
        (let [data (.-data snapshot)]
          (if (empty? data)
            (material/SliverToBoxAdapter

             .child
             (material/Container))

            (material/SliverMainAxisGroup

             .slivers
             [(material/SliverToBoxAdapter

               .child
               (material/Row

                .mainAxisAlignment material/MainAxisAlignment.spaceBetween

                .children
                [(material/Text
                  (.-recentActivity locales)
                  .softWrap true
                  .maxLines 2
                  .style headlineSmall)

                 (material/TextButton

                  .child
                  (material/Text
                   (.toUpperCase (.-viewJournal locales))

                   .style (.copyWith labelLarge
                                     .color secondary))

                  .onPressed go-to-journal)]))

              ;; TODO: Add recent activities
              ])))

        (material/SliverToBoxAdapter

         .child
         (material/SizedBox
          .height 80

          .width 80

          .child
          (material/CircularProgressIndicator))))))))

(defn home-widget
  [{:keys [go-to-add
           go-to-journal
           go-to-to-read-shelf
           go-to-reading-shelf
           go-to-favorite-shelf
           go-to-done-shelf]}]
  (flutter/widget
   :get {{{:flds [headlineMedium]} .-textTheme} material/Theme}
   :context context
   :let [locales (app-l10n/AppLocalizations.of context)]

   (material/CustomScrollView
    .slivers
    [;; App bar
     (material/SliverAppBar
      .pinned false

      .floating true

      .flexibleSpace
      (material/Center
       .child
       (material/Text
        (.-homeTitle locales)

        .style
        (.copyWith headlineMedium
                   .fontWeight material/FontWeight.bold))))

     (books-reading
      {:go-to-add go-to-add})

     (material/SliverToBoxAdapter
      .child
      (material/SizedBox
       .height 30))

     (shelves {:go-to-to-read-shelf go-to-to-read-shelf
               :go-to-reading-shelf go-to-reading-shelf
               :go-to-favorite-shelf go-to-favorite-shelf
               :go-to-done-shelf go-to-done-shelf})

     (material/SliverToBoxAdapter
      .child
      (material/SizedBox
       .height 30))

     (recent-activity
      {:go-to-journal go-to-journal})])))