(ns paginae.home.reading-carousel
  {:no-dynamic true}
  (:require ["package:carousel_slider/carousel_slider.dart" :as carousel]
            ["package:cljd_paginae/l10n/app_localizations.dart" :as app-l10n]
            ["package:flutter/material.dart" :as material]
            [cljd.flutter :as flutter]
            [paginae.book-details.book-details :as book-details]
            [paginae.image.widget :as image]
            [paginae.theme :as theme]))

(defn- reading-book-card
  "Card to display currently reading book"
  [book
   update-books]

  (flutter/widget
   :get {{{:flds [titleLarge bodyMedium]} .-textTheme} material/Theme}
   :context context
   :let [locales (app-l10n/AppLocalizations.of context)]
   :get [material/Navigator]

   (material/InkWell
    .onTap
    (fn []
      (let [_ (await (.push
                      navigator
                      (#/(material/MaterialPageRoute Object)
                       .builder
                       (flutter/build (book-details/book-details book nil)))))]
        (update-books))))

   .child
   (material/Card)

   .child
   (material/Container

    .padding
    (material/EdgeInsets.all 10))

   .child
   (material/Column
    .crossAxisAlignment
    material/CrossAxisAlignment.center

    .mainAxisAlignment
    material/MainAxisAlignment.spaceBetween)

   .children
   [;; Cover image
    (image/cover-image
     {:book book
      :placeholder-text (.-noCover locales)
      :bordered? false
      :clickable? false
      :on-click nil
      :width 175})

    (material/Column

     .children
     [ ;; Title
      (material/Text
       (:title book)

       .style
       (.copyWith titleLarge

                  .fontWeight
                  material/FontWeight.bold)

       .overflow
       material/TextOverflow.ellipsis)

      ;; Author
      (material/Text
       (:author book)

       .style
       bodyMedium

       .overflow
       material/TextOverflow.ellipsis)])

    ;; Progress
    (let [progress (:current-progress book)
          pages (:pages book)]

      (material/Column
       .spacing 10

       .children
       [(material/Row

         .mainAxisAlignment
         material/MainAxisAlignment.spaceBetween

         .children
         [(material/Text
           (.toUpperCase (.percentComplete locales (.round (* 100 progress)))))

          (material/Text
           (if (nil? pages)
             ""
             (.toUpperCase (.pageCount locales (.round (* pages progress))))))])

        ;; Progress bar
        (material/LinearProgressIndicator
         .value progress)]))]))

(defn reading-carousel
  "Widget to display currently reading books"
  [{:keys [books
           go-to-add
           on-pop]}]

  (flutter/widget
   :get {{{:flds [bodyMedium headlineSmall titleLarge titleMedium]} .-textTheme
          {:flds [primary onPrimary]} .-colorScheme} material/Theme}
   :context context
   :let [locales (app-l10n/AppLocalizations.of context)]

   (material/SliverToBoxAdapter)

   .child
   (material/Center)

   .child
   (if (empty? books)
     ;; If no books, action to add one
     (material/Column

      .spacing 10

      .children
      [(material/Text
        (.-noReading locales)

        .style
        (.copyWith
         titleLarge

         .fontFamily
         theme/sans-serif-font))

       (material/FilledButton
        .onPressed go-to-add

        .child
        (material/Text
         (.toUpperCase (.-addNewBook locales))

         .style
         (.copyWith titleMedium
                    .color onPrimary
                    .fontFamily theme/sans-serif-font
                    .fontWeight material/FontWeight.bold)))])

     ;; List the reading books 
     (material/Column

      .spacing 10

      .children
      [(material/Row
        .mainAxisAlignment
        material/MainAxisAlignment.spaceBetween

        .children
        [;; Section title
         (material/Text
          (.-currentlyReading locales)
          .softWrap true
          .maxLines 2
          .style headlineSmall)

         ;; Book count 
         (material/Text
          (.toUpperCase ^String ((.-booksInProgress locales) (count books)))

          .softWrap true

          .maxLines 2

          .style
          (.copyWith bodyMedium
                     .fontWeight material/FontWeight.bold
                     .color primary))])

       ;; Book carousel
       (carousel/CarouselSlider.builder
        .itemCount
        (count books)

        .options
        (carousel/CarouselOptions
         .height 400

         .initialPage 0

         .enableInfiniteScroll false)

        .itemBuilder
        (fn [_context idx _pageViewIdx]
          (let [book (nth books idx)]
            (material/Padding
             .padding (material/EdgeInsets.symmetric .horizontal 4)
             .child (reading-book-card book on-pop)))))]))))