(ns paginae.home.recent-activity
  {:no-dynamic true}
  (:require ["package:cljd_paginae/l10n/app_localizations.dart" :as app-l10n]
            ["package:flutter/material.dart" :as material]
            [cljd.flutter :as flutter]
            [paginae.common.activity-card :as common.activity-card]))

(defn recent-activity
  "Widget to display the most recent reading activity"
  [{:keys [activities
           go-to-journal]}]
  (flutter/widget
   :get {{{:flds [headlineSmall labelLarge]} .-textTheme
          {:flds [secondary]} .-colorScheme} material/Theme}
   :context context
   :let [locales (app-l10n/AppLocalizations.of context)]

   (if (empty? activities)
     (material/SliverToBoxAdapter

      .child
      (material/Container))

     (material/SliverMainAxisGroup

      .slivers
      [(material/SliverToBoxAdapter

        .child
        (material/Row

         .mainAxisAlignment material/MainAxisAlignment.spaceBetween

         .children
         [(material/Text
           (.-recentActivity locales)
           .softWrap true
           .maxLines 2
           .style headlineSmall)

          (material/TextButton

           .child
           (material/Text
            (.toUpperCase (.-viewJournal locales))

            .style (.copyWith labelLarge
                              .color secondary))

           .onPressed go-to-journal)]))

       (material/SliverList
        .delegate
        (material/SliverChildBuilderDelegate
         (fn [_context idx]
           (when (< idx (count activities))
             (let [entry (nth activities idx)]
               (common.activity-card/activity-card entry true))))))]))))
