(ns paginae.my-books.my-books
  {:no-dynamic true}
  (:require
   ["package:cljd_paginae/l10n/app_localizations.dart" :as app-l10n]
   ["package:flutter/material.dart" :as material]
   ["package:material_symbols_icons/symbols.dart" :as symbols]
   [cljd.flutter :as flutter]
   [paginae.database :as db]
   [paginae.my-books.book-card :as book-card]
   [paginae.theme :as theme]))


(defn- filter-button
  "Popup menu to select filter"
  []
  (flutter/widget
   :get {{{:flds [secondary onSecondary]} .-colorScheme} material/Theme}
   :get [:data-revision
         :filter-by]
   :context context
   :let [locales (app-l10n/AppLocalizations.of context)]

   (material/PopupMenuButton

    .icon
    (material/Icon
     symbols/Symbols.filter_alt

     .fill 1.0)

    .onSelected
    (fn [value]
      (reset! filter-by value)
      (swap! data-revision inc))

    .itemBuilder
    (fn [_builder-context]
      [ ;; Title
       (material/PopupMenuItem
        .enabled false

        .child
        (material/Text (.-filterBy locales)))

       ;; Finished
       (material/PopupMenuItem
        .value :done

        .child
        (material/ListTile

         .leading (material/Icon symbols/Symbols.check_circle)

         .title (material/Text (.-filterFinished locales))))

       ;; To-Read
       (material/PopupMenuItem
        .value :to-read

        .child
        (material/ListTile

         .leading (material/Icon symbols/Symbols.bookmark)

         .title (material/Text (.-filterToRead locales))))

       ;; Favorite
       (material/PopupMenuItem
        .value :favorite

        .child
        (material/ListTile

         .leading (material/Icon symbols/Symbols.favorite)

         .title (material/Text (.-filterFavorites locales))))

       ;; Reading
       (material/PopupMenuItem
        .value :reading

        .child
        (material/ListTile

         .leading (material/Icon symbols/Symbols.book_ribbon)

         .title (material/Text (.-filterReading locales))))

       ;; Reset
       (material/PopupMenuItem
        .value :reset

        .padding
        (material/EdgeInsets.all 8)

        .child
        (material/Container

         .padding
         (material/EdgeInsets.symmetric
          .horizontal 12
          .vertical 10)

         .decoration
         (material/BoxDecoration
          .color secondary

          .borderRadius
          (material/BorderRadius.circular 10))

         .child
         (material/Center

          .child
          (material/Text
           (.-resetFilter locales)

           .style
           (material/TextStyle
            .color onSecondary)))))]))))


(defn my-books-widget
  "Widget that shows the user's books"
  [filter-by-value]

  (flutter/widget
   :get {{{:flds [headlineSmall titleMedium]} .-textTheme
          {:flds [onBackground]} .-colorScheme} material/Theme}
   :context context
   :bind {:filter-by (atom filter-by-value)}
   :get [:data-revision
         :filter-by]
   :watch [filter filter-by
           refresh data-revision

           books (cond
                   (or (= :reset filter) (nil? filter))
                   (db/get-all-books)

                   (= :favorite filter)
                   (db/get-favorite-books)

                   :else
                   (db/get-books-by-status filter)) :default [] :refresh-on refresh]

   :let [portrait? (= (.-orientation (material/MediaQuery.of context)) material/Orientation.portrait)
         locales (app-l10n/AppLocalizations.of context)
         book-count (count books)]


   (material/CustomScrollView)

   .slivers
   [;; App bar
    (material/SliverAppBar
     .pinned false

     .floating true

     .centerTitle true

     .actions
     [(filter-button)]

     .title
     (material/Text
      (.-allMyBooks locales)

      .style
      (.copyWith
       headlineSmall

       .fontWeight
       material/FontWeight.bold)))

    (if (zero? book-count)
      (flutter/widget
       (material/SliverFillRemaining

        .hasScrollBody
        false)

       (material/Center)

       (material/Text
        (case filter
          :favorite (.-noFavorites locales)
          :done (.-noFinished locales)
          :to-read (.-noToRead locales)
          :reading (.-noReading locales)
          (.-noBooks locales))

        .textAlign
        material/TextAlign.center

        .style
        (.copyWith
         titleMedium

         .color
         (.withOpacity onBackground 0.7)

         .fontFamily
         theme/sans-serif-font)))


      (material/SliverGrid.builder
       .itemCount book-count

       .gridDelegate
       (material/SliverGridDelegateWithFixedCrossAxisCount
        .crossAxisCount (if portrait? 2 4)
        .crossAxisSpacing 10
        .mainAxisSpacing 5
        .childAspectRatio 0.45)

       .itemBuilder
       (fn [_context index]
         (book-card/book-card
          (nth books index)
          (fn []
            (swap! data-revision inc))))))]))