(ns paginae.common.book-editor.book-editor
  {:no-dynamic true}
  (:require
   ["package:cljd_paginae/l10n/app_localizations.dart" :as app-l10n]
   ["package:flutter/material.dart" :as material]
   ["package:flutter/widgets.dart" :as widgets]
   ["package:image_picker/image_picker.dart" :as image-picker]
   [cljd.flutter :as flutter]
   [paginae.common.async :as async]
   [paginae.common.book-editor.book-format :as book-format]
   [paginae.common.book-editor.form :as form]
   [paginae.common.book-editor.reading-status :as reading-status]
   [paginae.database :as db]
   [paginae.image.utils :as img-utils]
   [paginae.image.widget :as image]
   [paginae.types.book :as book-type]))

(defn- show-snackbar
  "Show a snackbar in the given context with the given message"
  [context
   message]
  (-> (material/ScaffoldMessenger.of context)
      (.showSnackBar
       (material/SnackBar
        .content (material/Text message))))
  nil)

(defn- save-cover-and-notify
  "Save the book cover after navigation has happened.
   On failure a snackbar is shown"
  [context
   {:keys [id] :as book}
   on-image-saved]
  (let [cover-result (await (async/try-await #(img-utils/save-book-cover book)))]
    (if (:ok cover-result)
      (do
        (on-image-saved)
        (await (async/try-await #(db/set-book-has-cover id))))
      (show-snackbar context (.-failedToSaveCover (app-l10n/AppLocalizations.of context))))))

(defn- add-cover
  "Pick an image to use as cover"
  []

  (let [picker (image-picker/ImagePicker.)]
    (some-> (await
             (.pickImage picker
                         .source image-picker/ImageSource.gallery
                         .maxWidth 800
                         .maxHeight 800
                         .imageQuality 85))
            .-path)))

(defn- ^material/PreferredSizeWidget app-bar
  "App bar"
  [{:keys [context
           on-cancel
           on-save]}]

  (let [locales (app-l10n/AppLocalizations.of context)
        colorScheme (.-colorScheme (material/Theme.of context))]

    (material/AppBar
     .title
     (material/Text (.-addToLibrary locales))

     .centerTitle true

     .leading
     (material/IconButton ;; Cancel button

      .icon
      (material/Icon material/Icons.close)

      .onPressed
      on-cancel

      .tooltip
      (.-cancel locales))

     .actions
     [;; Save book
      (material/FilledButton
       .onPressed
       (fn []
         (on-save))

       .child
       (material/Text
        (.-save locales))

       .style
       (material/ButtonStyle
        .backgroundColor
        (material/WidgetStatePropertyAll
         (.-surface colorScheme))

        .foregroundColor
        (material/WidgetStatePropertyAll
         (.-onBackground colorScheme))

        .padding
        (material/WidgetStatePropertyAll
         (material/EdgeInsets.all 15))))])))

(defn editor-widget
  "Body widget on the add book screen"
  [{:keys [book-atom
           title-controller
           author-controller
           pages-controller]}]

  (flutter/widget
   :get {{{:flds [background]} .-colorScheme} material/Theme}
   :context context

   (material/Container
    .margin
    (material/EdgeInsets.symmetric .horizontal 12 .vertical 0)

    .decoration
    (material/BoxDecoration
     .color background))

   (material/Center)

   (material/SingleChildScrollView)

   (material/Column
    .crossAxisAlignment
    material/CrossAxisAlignment.center

    .spacing 20)

   .children
   [;; Cover image
    (image/cover-image
     {:book @book-atom
      :placeholder-text (.-addCover (app-l10n/AppLocalizations.of context))
      :bordered? true
      :clickable? true
      :on-click (fn []
                  (let [cover (await (add-cover))]
                    (when cover
                      (swap! book-atom book-type/update-local-cover cover))))})

    ;; Form
    (form/form-card
     title-controller
     author-controller
     pages-controller)

    ;; Reading status
    (reading-status/status-card book-atom)

    ;; Book formats
    (book-format/format-card book-atom)]))

(defn- save-book
  "Validate and save book to database"
  [{:keys [^widgets/BuildContext context
           book-atom
           saving
           ^material/TextEditingController title-controller
           ^material/TextEditingController author-controller
           ^material/TextEditingController pages-controller
           on-navigation
           on-save
           on-image-saved]}]
  (when (not @saving)
    (reset! saving true)
    (try
      (let [new-title (.trim (.-text title-controller))
            new-author (.trim (.-text author-controller))
            empty-title? (not (seq new-title))
            empty-author? (not (seq new-author))
            locales (app-l10n/AppLocalizations.of context)]
        (cond
          empty-title?  (show-snackbar context (.-titleRequired locales))
          empty-author?  (show-snackbar context (.-authorRequired locales))
          :else (do
                  (swap! book-atom #(assoc %
                                           :title new-title
                                           :author new-author
                                           :pages (parse-long (.trim (.-text pages-controller)))
                                           :has-cover? (:local-cover? @book-atom)))
                  (let [insert-result (await (async/try-await #(on-save @book-atom)))]
                    (if (:ok insert-result)
                      (do
                        (when (.-mounted context)
                          (on-navigation)
                          (.pop (material/Navigator.of context) @book-atom))

                        (when (:cover-uri @book-atom)
                          (await (save-cover-and-notify context
                                                        @book-atom
                                                        on-image-saved))))

                      (when (.-mounted context)
                        (on-navigation)
                        (.pop (material/Navigator.of context))))))))
      (finally
        (reset! saving false)))))

(defn book-editor
  "Widget used for adding/editing a book"
  [{:keys [book
           on-navigation
           on-save]}]

  (flutter/widget
   :watch [_book-val (atom book) :as book-atom
           _saving? (atom false) :as saving]

   :managed [title-controller (material/TextEditingController
                               .text (:title book))
             author-controller (material/TextEditingController
                                .text (:author @book-atom))

             pages-controller (material/TextEditingController
                               .text (str (:pages @book-atom)))]

   :get [material/Navigator
         :data-revision]

   :context context

   (material/Scaffold
    .appBar
    (app-bar  {:context context
               :on-cancel (fn []
                            (.pop navigator))
               :on-save (fn []
                          (save-book {:context context
                                      :book-atom book-atom
                                      :saving saving
                                      :title-controller title-controller
                                      :author-controller author-controller
                                      :pages-controller pages-controller
                                      :on-navigation on-navigation
                                      :on-save on-save
                                      :on-image-saved (fn []
                                                        (swap! data-revision inc))}))})

    .body
    (editor-widget {:book-atom book-atom
                    :title-controller title-controller
                    :author-controller author-controller
                    :pages-controller pages-controller}))))