(ns paginae.common.book-editor.form
  {:no-dynamic true}
  (:require ["package:cljd_paginae/l10n/app_localizations.dart" :as app-l10n]
            ["package:flutter/material.dart" :as material]
            [cljd.flutter :as flutter]
            [paginae.common.number-input :as number-input]))

(defn- input-field
  "Input field for the book data"
  [{:keys [label 
           hint
           controller]}]

  (flutter/widget
   :get {{{:flds [surface]} .-colorScheme} material/Theme}

   (material/TextField
    .controller controller

    .decoration
    (material/InputDecoration
     .labelText label
     .hintText hint
     .filled true
     .fillColor surface

     .border
     (material/OutlineInputBorder
      .borderRadius
      (material/BorderRadius.circular 12)

      .borderSide
      material/BorderSide.none)))))

(defn form-card
  "Card that holds the form for the book info"
  [title-controller
   author-controller
   pages-controller]

  (flutter/widget
   :get {{{:flds [background surface]} .-colorScheme} material/Theme}
   :context context
   :let [locales (app-l10n/AppLocalizations.of context)]

   (material/Card
    .color
    background

    .child
    (material/Container
     .padding
     (material/EdgeInsets.all 24)

     .child
     (material/Column
      .spacing 16

      .children
      [(input-field {:label (.-bookTitle locales)
                     :hint (.-bookTitle locales)
                     :controller title-controller})

       (input-field {:label (.-bookAuthor locales)
                     :hint (.-bookAuthor locales)
                     :controller author-controller})

       (number-input/integer-input-field {:lower-limit 0
                                          :upper-limit 100000
                                          :controller pages-controller
                                          :label (.-totalPages locales)
                                          :locales locales
                                          :background-color surface})])))))