(ns paginae.book-details.activity-dialog
  {:no-dynamic true}
  (:require
   ["../l10n/app_localizations.dart" :as app-l10n]
   ["package:flutter/material.dart" :as material]
   ["package:flutter/widgets.dart" :as widgets]
   [cljd.flutter :as flutter]
   [paginae.common.number-input :as common.number-input]))

(defn add-activity-dialog
  "Dialog that permits the addition of a reading session"
  [{:keys [context
           ^material/TextEditingController controller
           book
           on-confirm]}]

  (material/showDialog
   .context context

   .builder
   (fn [dialog-context]

     (flutter/widget
      :let [locales (app-l10n/AppLocalizations.of dialog-context)
            theme (material/Theme.of dialog-context)
            color-scheme (.-colorScheme theme)
            text-theme (.-textTheme theme)
            pages (:pages book)
            has-pages? (not (nil? pages))]
      :watch [as-pages? (atom has-pages?) :as as-pages]

      (material/Dialog)

      .child
      (material/Padding
       .padding
       (material/EdgeInsets.symmetric .horizontal 10 .vertical 20))

      .child
      (material/Column
       .spacing 20

       .mainAxisSize material/MainAxisSize.min)

      .children
      [;; Title
       (material/Text
        (.-setReadingProgress locales)

        .style
        (.-titleLarge text-theme))

       ;; Input
       (material/Row
        .spacing 10

        .children
        [;; Text input
         (material/Flexible

          .child
          (if as-pages?
            (common.number-input/integer-input-field
             {:lower-limit 1
              :upper-limit pages
              :label (.-currentPage locales)
              :controller controller
              :locales locales})
            (common.number-input/float-input-field
             {:lower-limit 0.1
              :upper-limit 100.0
              :label (.-currentPercentage locales)
              :controller controller
              :locales locales})))

         ;; Label (pages or percentage)
         (if has-pages?
           (material/DropdownMenu
            .initialSelection
            as-pages?

            .dropdownMenuEntries
            [(material/DropdownMenuEntry .value true .label (.-pageUnit locales))
             (material/DropdownMenuEntry .value false .label "%")]

            .onSelected
            (fn [new-value]
              (reset! as-pages new-value)))

           (material/Text "%"))])

       ;; Buttons
       (material/Row
        .mainAxisAlignment material/MainAxisAlignment.end

        .children
        [;; Cancel button
         (material/TextButton

          .child
          (material/Text
           (.-cancel locales)

           .style
           (.-labelLarge text-theme))

          .onPressed
          (fn []
            (.-text! controller "")
            (.pop (widgets/Navigator.of dialog-context))))

         ;; Save button
         (material/TextButton

          .child
          (material/Text
           (.-save locales)

           .style
           (.copyWith
            (.-labelLarge text-theme)

            .color
            (.-primary color-scheme)))

          .onPressed
          (fn []
            (let [value (parse-double (.trim (.-text controller)))]
              (when (and value (pos? value))
                (let [progress (if as-pages?
                                 (/ value pages)
                                 (/ value 100.0))]
                  (await (on-confirm progress))
                  (.-text! controller "")
                  (.pop (widgets/Navigator.of dialog-context) progress))))))])]))))