(ns paginae.book-details.book-details
  {:no-dynamic true}
  (:require ["package:cljd_paginae/l10n/app_localizations.dart" :as app-l10n]
            ["package:flutter/material.dart" :as material]
            ["package:flutter/widgets.dart" :as widgets]
            ["package:material_symbols_icons/symbols.dart" :as symbols]
            [cljd.flutter :as flutter]
            [paginae.book-details.activity-dialog :as book-details.activity-dialog]
            [paginae.book-details.notes.add-note-dialog :as add-note-dialog]
            [paginae.book-details.notes.note-card :as note-card]
            [paginae.book-details.reading-progress :as book-details.reading-progress]
            [paginae.book-details.share-dialog :as share-dialog]
            [paginae.book-details.timer.reading-timer :as book-details.reading-timer]
            [paginae.common.activity-card :as common.activity-card]
            [paginae.common.book-editor.book-editor :as book-editor]
            [paginae.common.confirm-delete-dialog :as common.confirm-dialog]
            [paginae.database :as db]
            [paginae.image.utils :as img-utils]
            [paginae.image.widget :as image]
            [paginae.types.book :as book-type]))

(defn- action-button
  "Pill button for actions"
  [{:keys [on-pressed
           icon
           text
           ^material/Color background
           ^material/Color foreground]}]
  (material/ElevatedButton
   .onPressed on-pressed

   .child
   (material/Row
    .mainAxisAlignment material/MainAxisAlignment.center

    .spacing 10

    .children
    [;; Icon
     (material/Icon icon)
     ;; Text
     (material/Text text)])

   .style
   (material/ButtonStyle
    .backgroundColor
    (material/WidgetStatePropertyAll background)

    .foregroundColor
    (material/WidgetStatePropertyAll foreground)

    .padding
    (material/WidgetStatePropertyAll
     (material/EdgeInsets.all 15)))))

(defn- app-bar
  "App bar for the book details screen"
  [context
   book-atom
   notes
   activities]

  (let [locales (app-l10n/AppLocalizations.of context)
        color-scheme (.-colorScheme (material/Theme.of context))]
    (material/AppBar
     .leading
     (material/IconButton
      .icon
      (material/Icon symbols/Symbols.arrow_back)

      .tooltip (.-goBack locales)

      .onPressed
      (fn [] (.pop (widgets/Navigator.of context))))

     .actions
     [;; Favorite button
      (material/IconButton
       .icon
       (material/Icon
        symbols/Symbols.favorite

        .fill
        (if (:favorite @book-atom) 1.0 0.0)

        .color
        (if (:favorite @book-atom)
          (.-primary color-scheme)
          (.-onSurface color-scheme)))

       .tooltip
       (if (:favorite @book-atom)
         (.-unsetFavorite locales)
         (.-setFavorite locales))

       .onPressed
       (fn []
         (let [new-status (not (:favorite @book-atom))]
           (swap! book-atom #(book-type/update-favorite-status % new-status))
           (await (db/update-book @book-atom)))))

      ;; Edit button
      (material/IconButton
       .icon
       (material/Icon
        symbols/Symbols.edit

        .fill
        1.0)

       .tooltip
       (.-edit locales)

       .onPressed
       (fn []
         (let [updated (await
                        (.push
                         (material/Navigator.of context)
                         (#/(material/MaterialPageRoute Object)
                          .builder
                          (flutter/build
                           (book-editor/book-editor {:book @book-atom
                                                     :on-save db/update-book
                                                     :on-navigation #()})))))]
           (when updated
             (reset! book-atom updated)))
         nil))

      ;; Share button
      (material/IconButton
       .icon
       (material/Icon
        symbols/Symbols.share

        .fill
        1.0)

       .tooltip
       (.-share locales)

       .onPressed
       (fn []
         (share-dialog/share-dialog @book-atom
                                    notes
                                    activities
                                    context)))

      ;; Delete button
      (material/IconButton
       .icon
       (material/Icon
        symbols/Symbols.delete

        .color
        material/Colors.red

        .fill
        1.0)

       .tooltip
       (if (:favorite @book-atom)
         (.-unsetFavorite locales)
         (.-setFavorite locales))

       .onPressed
       (fn []
         (common.confirm-dialog/confirm-delete-dialog
          {:title ((.-deleteBookTitle locales) (:title @book-atom))
           :content ""
           :context context
           :on-confirm (fn []
                         (let [deletion-result (await (db/delete-book (:id @book-atom)))]
                           (when deletion-result
                             (when (:has-cover? @book-atom)
                               (img-utils/delete-cover (:id @book-atom)))
                             (.pop (material/Navigator.of context)))))})))])))

(defn book-details
  "Widget that shows the details of a book"
  [^book-type/Book book-value
   session]

  (flutter/widget
   :get
   {{{:flds [headlineSmall titleMedium titleLarge]} .-textTheme
     {:flds [primary onPrimary secondary onSecondary tertiary onTertiary]} .-colorScheme} material/Theme}
   :context context
   :let [locales (app-l10n/AppLocalizations.of context)]
   :get [material/Navigator
         :data-revision]
   :watch [book (atom book-value) :as book-atom
           revision data-revision
           notes (db/get-book-notes (:id book)) :default [] :refresh-on revision
           activities (db/get-book-activities (:id book)) :default [] :refresh-on revision
           _checked-session? (atom nil) :as checked-session]
   :managed [note-controller (material/TextEditingController)
             activity-controller (material/TextEditingController)]

   (do
     (.addPostFrameCallback
      (widgets/WidgetsBinding.instance)
      (fn [_]
        (when (and session (not @checked-session))
          (reset! checked-session true)
          (let [result (await (.push navigator
                                     (#/ (material/MaterialPageRoute Object)
                                      .builder
                                      (flutter/build
                                       (book-details.reading-timer/reading-timer book session)))))]
            (when result
              (swap! book-atom #(book-type/update-current-progress % result))
              (swap! data-revision inc))))))

     (material/Scaffold
      .appBar
      (app-bar context
               book-atom
               notes
               activities)

      .body
      (material/Container
       .padding
       (material/EdgeInsets.all 10)

       .child
       (material/SingleChildScrollView

        .child
        (material/Column
         .crossAxisAlignment
         material/CrossAxisAlignment.center

         .spacing 10

         .children
         [;; Cover image
          (image/cover-image
           {:book book
            :placeholder-text (.-noCover locales)
            :bordered? false
            :clickable? false
            :width 200})

          ;; Title
          (material/Text
           (:title book)

           .style headlineSmall

           .textAlign
           material/TextAlign.center)

          ;; Author
          (material/Text
           (.byAuthor locales (if (nil? (:author book)) (.-unknown locales) (:author book)))

           .style
           (.copyWith titleMedium .fontStyle material/FontStyle.italic))

          (material/SizedBox .height 20)

          ;; Progress circle
          (book-details.reading-progress/reading-progress
           {:book book
            :mark-as-started
            (fn []
              (reset! book-atom (book-type/update-status book :reading))
              (await (db/update-book @book-atom)))})

          (material/SizedBox .height 20)
          ;; Action button. Timer
          (action-button
           {:on-pressed
            (fn []
              (let [result (await (.push navigator
                                         (#/ (material/MaterialPageRoute Object)
                                          .builder
                                          (flutter/build
                                           (book-details.reading-timer/reading-timer book nil)))))]
                (when result
                  (swap! book-atom #(book-type/update-current-progress % result))
                  (swap! data-revision inc))))
            :icon symbols/Symbols.timer
            :text (.-readingTimer locales)
            :background primary
            :foreground onPrimary})
          ;; Action button. Update progress
          (action-button {:on-pressed
                          (fn []
                            (let [data (await (book-details.activity-dialog/add-activity-dialog
                                               {:context context
                                                :controller activity-controller
                                                :book book
                                                :on-confirm
                                                (fn [progress]
                                                  (await
                                                   (db/insert-book-activity {:book-id (:id book)
                                                                             :progress progress})))}))]
                              (when data
                                (swap! book-atom #(book-type/update-current-progress % data))
                                (swap! data-revision inc))))
                          :icon symbols/Symbols.edit_note
                          :text (.-updateProgress locales)
                          :background secondary
                          :foreground onSecondary})
          ;; Action button. Add note
          (action-button
           {:on-pressed (fn []
                          (let [note (await (add-note-dialog/add-note-dialog
                                             context
                                             note-controller))]
                            (when note
                              (await (db/insert-book-note note (:id book)))
                              (swap! data-revision inc))))
            :icon symbols/Symbols.add
            :text (.-addNoteAction locales)
            :background tertiary
            :foreground onTertiary})
          (material/SizedBox .height 20)

          ;; Notes
          (flutter/widget
           :when (seq notes)

           (material/Text (.-notesSection locales) .style titleLarge))

          (material/ListView

           .shrinkWrap
           true

           .physics
           (widgets/NeverScrollableScrollPhysics)

           .children
           (map #(note-card/note-card
                  {:context context
                   :note %
                   :book-name (:title book)
                   :note-controller note-controller})
                notes))

          ;; Activities
          (flutter/widget
           :when (seq activities)

           (material/Text (.-activitySection locales) .style titleLarge))

          (material/ListView .shrinkWrap
                             true
                             .physics
                             (widgets/NeverScrollableScrollPhysics)
                             .children
                             (map #(common.activity-card/activity-card
                                    {:activity %
                                     :book book}
                                    false) activities))])))))))
