(ns paginae.book-details.reading-timer
  {:no-dynamic true}
  (:require
   ["../l10n/app_localizations.dart" :as app-l10n]
   ["dart:async" :as dart:async]
   ["package:flutter/material.dart" :as material]
   ["package:flutter/widgets.dart" :as widgets]
   ["package:material_symbols_icons/symbols.dart" :as symbols]
   [cljd.flutter :as flutter]
   [paginae.book-details.activity-dialog :as book-details.activity-dialog]
   [paginae.book-details.reading-session :as reading-session]
   [paginae.database :as db]
   [paginae.theme :as theme]))

(defn- now-in-seconds
  "Return the current DateTime in seconds since Epoch"
  []
  (-> (dart:core/DateTime.now)
      .toUtc
      .-millisecondsSinceEpoch
      (/ 1000)
      .round))

(defn elapsed-seconds
  "Calculate the seconds that have passed since a given time"
  [start-time]
  (- (now-in-seconds) start-time))

(defn- start-timer
  "Start the timer"
  [timer-atom
   ticker-atom]
  (reset! timer-atom
          (dart:async/Timer.periodic
           (dart:core/Duration .seconds 1)
           (fn [_]
             (swap! ticker-atom inc)))))

(defn- pause-timer
  "Pause the timer"
  [timer-atom]
  (when-let [^dart:async/Timer timer @timer-atom]
    (.cancel timer)
    (reset! timer-atom nil)))

(defn- timer-widget
  "Widget that shows the reading time"
  [{:keys [start-time
           elapsed-time
           running?
           ticker-atom]}]
  (flutter/widget
   :get {{{:flds [displayMedium]} .-textTheme} material/Theme}
   :watch [_ticker ticker-atom]

   (material/Text
    (if (nil? start-time)
      "00:00:00"
      (let [current-time (if running? (elapsed-seconds start-time) 0)
            seconds (+ elapsed-time current-time)
            hours (.padLeft (.toString (quot seconds 3600)) 2 "0")
            mins (.padLeft (.toString (mod (quot seconds 60) 60)) 2 "0")
            secs (.padLeft (.toString (mod seconds 60)) 2 "0")]

        (str hours ":" mins ":" secs)))

    .style
    (.copyWith
     displayMedium

     .fontFamily
     theme/sans-serif-font))))

(defn- play-pause-button
  "Widget for the play/pause button"
  [{:keys [running-atom
           on-play
           on-pause]}]

  (flutter/widget
   :get {{{:flds [surface onSurface]} .-colorScheme} material/Theme}

   (material/IconButton
    .icon
    (material/Icon
     (if @running-atom
       symbols/Symbols.pause
       symbols/Symbols.play_arrow))

    .iconSize 80

    .style
    (material/ButtonStyle
     .backgroundColor
     (material/WidgetStatePropertyAll surface)

     .foregroundColor
     (material/WidgetStatePropertyAll onSurface))

    .onPressed
    (fn []
      (if @running-atom
        (on-pause)
        (on-play))
      (swap! running-atom not)))))

(defn- quick-note-widget
  "Widget for adding a quick note (input field and button)"
  [controller
   on-pressed]
  (flutter/widget
   :context context
   :get {{{:flds [surface primary onPrimary]} .-colorScheme} material/Theme}
   :let [locales (app-l10n/AppLocalizations.of context)]

   (material/Column
    .crossAxisAlignment
    material/CrossAxisAlignment.stretch

    .children
    [(material/TextField
      .controller
      controller

      .minLines 5
      .maxLines 5

      .decoration
      (material/InputDecoration
       .hintText (.-quickNoteHint locales)
       .filled true
       .fillColor surface

       .border
       (material/OutlineInputBorder
        .borderRadius
        (material/BorderRadius.circular 12)

        .borderSide
        material/BorderSide.none)))

     (material/ElevatedButton
      .child
      (material/Text (.-saveNote locales))

      .style
      (material/ButtonStyle
       .backgroundColor
       (material/WidgetStateProperty.all primary)

       .foregroundColor
       (material/WidgetStateProperty.all onPrimary))

      .onPressed
      on-pressed)])))

(defn reading-timer
  "Widget that shows a reading session timer"
  [book
   session]

  (flutter/widget
   :context context
   :managed [note-controller (material/TextEditingController)
             progress-controller (material/TextEditingController)
             timer-atom (atom nil) :dispose pause-timer
             running-atom (atom (:running session)) :dispose nil
             start-time-atom (atom (:started-at session)) :dispose nil
             elapsed-time-atom (atom (or 0 (:accumulated session))) :dispose nil
             ticker-atom (atom 0) :dispose nil
             _boot (do
                     (when (:running session)
                       (start-timer timer-atom ticker-atom))
                     nil) :dispose nil]
   :watch [elapsed-time elapsed-time-atom
           start-time start-time-atom]
   :let [locales (app-l10n/AppLocalizations.of context)
         portrait? (= material/Orientation.portrait (.-orientation (material/MediaQuery.of context)))
         start-session (fn []
                         (reset! start-time-atom (now-in-seconds))
                         (reading-session/save-session
                          {:started-at (now-in-seconds)
                           :accumulated elapsed-time
                           :running true
                           :updated-at (now-in-seconds)
                           :book-id (:id book)})
                         (start-timer timer-atom ticker-atom))
         pause-session (fn []
                         (swap! elapsed-time-atom #(+ % (- (now-in-seconds) start-time)))
                         (reading-session/save-session
                          {:started-at start-time
                           :accumulated @elapsed-time-atom
                           :running false
                           :updated-at (now-in-seconds)
                           :book-id (:id book)})
                         (pause-timer timer-atom))]

   (material/Scaffold
    .appBar
    (material/AppBar
     .leading
     (material/IconButton
      .icon
      (material/Icon symbols/Symbols.arrow_back)

      .onPressed
      (fn []
        (pause-timer timer-atom)
        (reading-session/delete-session)
        (.pop (widgets/Navigator.of context))))

     .actions
     [(material/ElevatedButton
       .child
       (material/Row
        .spacing 10
        .children
        [(material/Icon symbols/Symbols.check)
         (material/Text (.-done locales))])

       .onPressed
       (fn []
         (let [data (await (book-details.activity-dialog/add-activity-dialog
                            {:context context
                             :controller progress-controller
                             :book book
                             :on-confirm
                             (fn [progress]
                               (await
                                (db/insert-book-activity
                                 {:book-id (:id book)
                                  :progress progress
                                  :reading-time (if (nil? start-time)
                                                  nil
                                                  (+ elapsed-time (elapsed-seconds start-time)))})))}))]
           (when (and data (.-mounted context))
             (reading-session/delete-session)
             (.pop (widgets/Navigator.of context) data)))))])

    .body
    (material/Padding
     .padding
     (material/EdgeInsets.all 20)

     .child
     (material/Center

      .child
      (letfn [(on-note-save []
                (let [note (.trim (.-text note-controller))]
                  (when (seq note)
                    (await (db/insert-book-note note (:id book)))
                    (.-text! note-controller "")
                    nil)))]
        (if portrait?
          (material/Column
           .spacing 30

           .crossAxisAlignment
           material/CrossAxisAlignment.center

           .children
           [(timer-widget
             {:start-time start-time
              :elapsed-time elapsed-time
              :running? @running-atom
              :ticker-atom ticker-atom})

            (play-pause-button
             {:running-atom running-atom
              :on-play start-session
              :on-pause pause-session})

            (quick-note-widget
             note-controller
             on-note-save)])

          (material/Row
           .crossAxisAlignment
           material/CrossAxisAlignment.center

           .children
           [(material/Expanded

             .child
             (material/Column

              .children
              [(timer-widget
                {:start-time start-time
                 :elapsed-time elapsed-time
                 :running? @running-atom
                 :ticker-atom ticker-atom})

               (play-pause-button
                {:running-atom running-atom
                 :on-play start-session
                 :on-pause pause-session})]))

            (material/Expanded
             .child
             (quick-note-widget
              note-controller
              on-note-save))]))))))))