(ns paginae.common.image.widget
  {:no-dynamic true}
  (:require [cljd.flutter :as flutter]
            ["package:flutter/material.dart" :as material]
            [paginae.common.image.utils :as img-utils]
            ["dart:io" :as io]
            ["package:cljd_paginae/l10n/app_localizations.dart" :as app-l10n]))

(defn cover-placeholder
  "Widget used for when there is no cover image"
  [{:keys [text
           width
           height]}]
  (flutter/widget
   :get {{{:flds [surfaceVariant onSurfaceVariant]} .-colorScheme} material/Theme}

   (material/ClipRRect
    .borderRadius
    (material/BorderRadiusGeometry.circular 16))

   .child
   (material/Container
    .width width
    .height height
    .color surfaceVariant)

   .child
   (material/Column
    .mainAxisAlignment
    material/MainAxisAlignment.center)

   .children
   [;; No image icon
    (material/Icon
     material/Icons.image_outlined

     .size 40

     .color
     (.withOpacity onSurfaceVariant 0.5))

    (material/SizedBox
     .height 8)

    ;; Placeholder text
    (material/Text
     text

     .style
     (material/TextStyle
      .color
      (.withOpacity onSurfaceVariant 0.7)))]))

(defn- bordered-wrapper
  "Wrapper widget for a bordered child"
  [child]

  (flutter/widget
   :get {{{:flds [onSurface]} .-colorScheme} material/Theme}

   (material/Container

    .decoration
    (material/BoxDecoration
     .border
     (material/Border.all
      .width 2.0
      .color onSurface)

     .borderRadius
     (material/BorderRadiusGeometry.circular 16)))

   .child
   child))

(defn- clickable-wrapper
  "Wrapper for when the cover is clickable"
  [on-click
   child]
  (material/InkWell
   .onTap on-click
   .child child))

(defn cover-image
  "Widget that shows the cover image of a book"
  [{:keys [book
           placeholder-text
           bordered?
           clickable?
           on-click
           width]}]

  (flutter/widget
   :context context
   :get [:data-revision]
   :watch [revision data-revision]
   :let [locales (app-l10n/AppLocalizations.of context)

         img-width (or width 140)
         img-height (* img-width (/ 10 7))

         local-path (when (and (:local-cover? book)
                               book
                               (:has-cover? book))
                      (if (:cover-uri book)
                        (:cover-uri book)
                        (img-utils/cover-path (:id book))))

         placeholder
         (cover-placeholder {:text placeholder-text
                             :width img-width
                             :height img-height})

         image-widget
         (cond
           (and local-path (not-empty local-path))
           (material/Image.file
            (io/File. local-path)

            .key (material/ValueKey revision)

            .width img-width

            .height img-height

            .fit material/BoxFit.cover

            .errorBuilder
            (fn [_context _error _stack-trace]
              (cover-placeholder {:text placeholder-text
                                  :width img-width
                                  :height img-height})))

           (and (not (:local-cover? book)) (:cover-uri book))
           (material/Image.network
            (:cover-uri book)
            .width img-width
            .height img-height
            .fit material/BoxFit.cover
            .loadingBuilder
            (fn [_context child progress]
              (if (nil? progress)
                child
                (cover-placeholder {:text (.-loading locales)
                                    :width img-width
                                    :height img-height})))
            .errorBuilder
            (fn [_context _error _stack-trace]
              (cover-placeholder {:text placeholder-text
                                  :width img-width
                                  :height img-height})))

           :else
           (if bordered?
             (bordered-wrapper placeholder)
             placeholder))

         clipped
         (material/ClipRRect
          .borderRadius (material/BorderRadiusGeometry.circular 16)
          .child image-widget)

         clickable
         (if clickable?
           (clickable-wrapper on-click clipped)
           clipped)]

   clickable))