(ns paginae.widgets-test
  {:no-dynamic true}
  (:require [cljd.test :refer [deftest]]
            [paginae.common.badges :as badges]
            ["package:flutter/material.dart" :as material]
            ["package:flutter_test/flutter_test.dart" :as ft]))

(defn- pump-in-app
  "Wrap a widget in a MaterialApp and pump it."
  [pump-widget widget]
  (pump-widget
   (material/MaterialApp
    .home widget)))

(deftest badges-widget-test
  :tags [:widget]
  :runner ^{:clj-kondo/ignore [:unresolved-symbol]} (ft/testWidgets [tester])
  (let [^ft/WidgetTester {:flds [pumpWidget]} tester]
    (await
     (pump-in-app
      pumpWidget
      (material/Row
       .children
       [(badges/badge :done)
        (badges/badge :to-read)
        (badges/badge :favorite)
        (badges/badge :reading)])))
    ;; every badge renders an Icon; the row should render all four
    (ft/expect (ft/find.byType material/Icon) (ft/findsNWidgets 4))))