(ns paginae.book-details.notes.note-card
  {:no-dynamic true}
  (:require
   ["package:cljd_paginae/l10n/app_localizations.dart" :as app-l10n]
   ["package:flutter/material.dart" :as material]
   ["package:intl/intl.dart" :as intl]
   ["package:material_symbols_icons/symbols.dart" :as symbols]
   ["package:share_plus/share_plus.dart" :as share_plus]
   [cljd.flutter :as flutter]
   [paginae.book-details.notes.add-note-dialog :as add-note-dialog]
   [paginae.common.confirm-delete-dialog :as common.confirm-dialog]
   [paginae.database :as db]
   [paginae.types.note :as note-type]))

(defn note-card
  "Card for displaying a note"
  [{:keys [context
           note
           book-name
           ^material/TextEditingController note-controller]}]

  (flutter/widget
   :let [locales (app-l10n/AppLocalizations.of context)]
   :get {{{:flds [labelLarge bodyLarge]} .-textTheme
          {:flds [secondary onSurface]} .-colorScheme} material/Theme}
   :get [:data-revision]
   :key (:id note)

   (material/Card
    .margin
    (material/EdgeInsets.only .bottom 20))

   .child
   (material/ConstrainedBox
    .constraints
    (material/BoxConstraints .minHeight 100))

   .child
   (material/Padding
    .padding
    (material/EdgeInsets.all 10))

   .child
   (material/Column
    .spacing
    10
    .crossAxisAlignment
    material/CrossAxisAlignment.stretch)

   .children
   [;; Title
    (material/Row
     .mainAxisAlignment
     material/MainAxisAlignment.spaceBetween

     .children
     [;; Note title
      (material/Text
       (.toUpperCase (.-note locales))

       .style
       (.copyWith labelLarge

                  .color secondary))

      ;; Note's date
      (material/Text
       (.format
        (intl/DateFormat.yMMMd)
        (:created-at note))

       .style
       (.copyWith
        labelLarge

        .color
        (.withOpacity onSurface 0.7)))])

    ;; Note's contents
    (material/Text
     (:contents note)

     .textAlign
     material/TextAlign.start

     .style
     bodyLarge)

    ;; Actions
    (material/Row
     .spacing 10

     .children
     [;; Edit button
      (material/TextButton

       .child
       (material/Row
        .spacing 5

        .children
        [(material/Icon
          symbols/Symbols.edit

          .color
          onSurface)

         (material/Text
          (.toUpperCase (.-edit locales))

          .style
          labelLarge)])

       .onPressed
       (fn []
         (.-text! note-controller (:contents note))
         (let [new-contents (await (add-note-dialog/add-note-dialog context note-controller))]
           (when new-contents
             (await (db/update-book-note
                     (note-type/update-contents note new-contents)))
             (swap! data-revision inc)))))

      ;; Share button
      (material/TextButton

       .child
       (material/Row
        .spacing 5

        .children
        [(material/Icon
          symbols/Symbols.share

          .color
          onSurface)

         (material/Text
          (.toUpperCase (.-share locales))

          .style
          labelLarge)])

       .onPressed
       (fn []
         (.share share_plus/SharePlus.instance
                 (share_plus/ShareParams.
                  .text
                  (.shareNoteText locales book-name (:contents note))))
         nil))

      ;; Delete button
      (material/TextButton

       .child
       (material/Row
        .spacing 5

        .children
        [(material/Icon
          symbols/Symbols.delete

          .color
          material/Colors.red)

         (material/Text
          (.toUpperCase (.-delete locales))

          .style
          (.copyWith
           labelLarge

           .color
           material/Colors.red))])
       .onPressed
       (fn []
         (common.confirm-dialog/confirm-delete-dialog
          {:title (.-removeNoteTitle locales)
           :content ""
           :context context
           :on-confirm
           (fn []
             (let [_ (await (db/delete-note (:id note)))]
               (swap! data-revision inc)))})))])]))