(ns paginae.journal.journal
  {:no-dynamic true}
  (:require
   ["package:cljd_paginae/l10n/app_localizations.dart" :as app-l10n]
   ["package:flutter/material.dart" :as material]
   ["package:flutter/painting.dart" :as painting]
   ["package:material_symbols_icons/symbols.dart" :as symbols]
   ["package:table_calendar/table_calendar.dart" :as calendar]
   [cljd.flutter :as flutter]
   [paginae.common.activity-card :as common.activity-card]
   [paginae.database :as db]))


(defn- day-key
  "Return a vector [year month day] uniquely identifying a day"
  [^dart:core/DateTime day]
  [(.-year day) (.-month day) (.-day day)])

(defn- activity-day-key
  "Return the day-key of an activity data entry"
  [data]
  (day-key (:date (:activity data))))

(defn- starting-day-of-week
  "Get the starting day of week. If locale is english, sunday, otherwise monday"
  [^material/Locale locale]
  (if (= (.-languageCode locale) "en")
    calendar/StartingDayOfWeek.sunday
    calendar/StartingDayOfWeek.monday))

(defn- journal-calendar
  "Widget that displays a calendar with reading data"
  [{:keys [^dart:core/DateTime today
           first-day
           locale
           grouped-activities
           on-page-changed]}]
  (flutter/widget
   :get [:focused-day-atom
         :selected-day-atom]
   :watch [^dart:core/DateTime focused-day focused-day-atom]

   :get {{{:flds [labelLarge]} .-textTheme
          {:flds [primary secondary onSecondary]} .-colorScheme} material/Theme}

   (calendar/TableCalendar
    .focusedDay
    focused-day

    .currentDay
    today

    .selectedDayPredicate
    (fn [day]
      (calendar/isSameDay day @selected-day-atom))

    .firstDay
    first-day

    .lastDay
    today

    .calendarFormat
    calendar/CalendarFormat.month

    .shouldFillViewport
    false

    .startingDayOfWeek
    (starting-day-of-week locale)

    .eventLoader
    (fn [^dart:core/DateTime day]
      (get grouped-activities (day-key day) []))

    .calendarStyle
    (calendar/CalendarStyle
     .outsideDaysVisible false

     .selectedTextStyle
     (.copyWith
      labelLarge

      .color
      onSecondary)

     .defaultTextStyle
     labelLarge

     .selectedDecoration
     (material/BoxDecoration
      .color secondary

      .shape material/BoxShape.circle)

     .markerDecoration
     (material/BoxDecoration
      .color primary

      .shape material/BoxShape.circle))

    .locale
    (.toString locale)

    .weekendDays
    []

    .rangeSelectionMode
    calendar/RangeSelectionMode.disabled

    .onPageChanged
    (fn [^dart:core/DateTime day]
      (reset! focused-day-atom day)
      (on-page-changed))

    .headerStyle
    (calendar/HeaderStyle
     .titleCentered
     true

     .formatButtonVisible
     false

     .rightChevronIcon
     (let [same-month (= (.-month today) (.-month focused-day))
           same-year (= (.-year today) (.-year focused-day))]

       (if (not (and same-month same-year))
         (material/Icon symbols/Symbols.chevron_right)
         (material/Container))))

    .onDaySelected
    (fn [selected _focused]
      (reset! selected-day-atom selected)))))

(defn- activities-by-day
  "List the activities of a given day"
  [grouped-activities
   day
   context]
  (let [day-activities (get grouped-activities (day-key day) [])
        locales (app-l10n/AppLocalizations.of context)
        theme (material/Theme.of context)]


    (if (empty? day-activities)
      [(material/Text
        (.-noActivityThatDay locales)

        .style
        (.copyWith
         (.-bodyMedium (.-textTheme theme))

         .color
         (.withOpacity
          (.-onSurface (.-colorScheme  theme))
          0.6)))]

      (map #(common.activity-card/activity-card % true) day-activities))))

(defn journal-widget
  "Widget to show the reading activity"
  []
  (flutter/widget
   :context context
   :get {{{:flds [headlineSmall]} .-textTheme} material/Theme} 
   :bind {:selected-day-atom (atom (dart:core/DateTime.now))
          :focused-day-atom (atom (dart:core/DateTime.now))}
   :get [:selected-day-atom
         :focused-day-atom]
   :watch [selected-day selected-day-atom
           refresh-count (atom 0) :as refresh-day
           activities (db/get-activities-by-month
                       (.-month ^dart:core/DateTime @focused-day-atom)
                       (.-year ^dart:core/DateTime @focused-day-atom)) :default [] :refresh-on refresh-count
           first-day (db/get-first-activity-date) :default (dart:core/DateTime.now)]
   :let [today (dart:core/DateTime.now)
         locale (material/Localizations.localeOf context)
         portrait? (= (.-orientation (material/MediaQuery.of context)) material/Orientation.portrait)
         locales (app-l10n/AppLocalizations.of context)
         grouped-activities (group-by activity-day-key activities)]

   (material/Scaffold

    .appBar
    (if portrait?
      (material/AppBar

       .title
       (material/Text
        (.-journalTitle locales)

        .style
        (.copyWith
         headlineSmall

         .fontWeight
         material/FontWeight.bold))

       .centerTitle
       true)
      nil))

   .body
   (if portrait?
     (material/SingleChildScrollView

      .child
      (material/Column

       .children
       (into
        [(journal-calendar
          {:focused-day-atom focused-day-atom
           :selected-day-atom selected-day-atom
           :today today
           :first-day first-day
           :locale locale
           :grouped-activities grouped-activities
           :on-page-changed (fn [] (swap! refresh-day inc))})]
        (activities-by-day grouped-activities selected-day context))))

     (material/Row
      .children
      [(material/Expanded
        .child
        (journal-calendar
         {:focused-day-atom focused-day-atom
          :selected-day-atom selected-day-atom
          :today today
          :first-day first-day
          :locale locale
          :grouped-activities grouped-activities
          :on-page-changed (fn [] (swap! refresh-day inc))}))

       (material/Expanded
        .child
        (material/SingleChildScrollView
         .scrollDirection
         painting/Axis.vertical

         .child
         (material/Column
          .children
          (activities-by-day grouped-activities selected-day context))))]))))
