(ns paginae.image.utils
  (:require ["package:path_provider/path_provider.dart" :as path-provider]
            ["package:path/path.dart" :as path]
            ["package:image/image.dart" :as img]
            ["dart:io" :as io]
            ["package:flutter/foundation.dart" :as foundation]
            ["dart:async" :as async]))

(defonce image-directory-path (atom nil))

(defn init-image-directory
  "Set the image directory path"
  []
  (let [^io/Directory dir (await (path-provider/getApplicationDocumentsDirectory))]
    (reset! image-directory-path (.-path dir))))

(defn cover-path
  "Return the cover image path based on the id"
  [id]
  (path/join @image-directory-path (str id ".jpg")))

(def IMAGE-MAX-WIDTH
  "Maximum width in pixels for a saved image"
  300)

(defn- ^async/Future resize-and-save-image
  "Resize an image to a set width and save it to disk"
  [input-bytes output-path]
  (let [decoded (img/decodeImage input-bytes)]
    (when decoded
      (let [resized (img/copyResize decoded .width IMAGE-MAX-WIDTH)
            jpg (img/encodeJpg resized)]
        (await (.writeAsBytes (io/File. output-path) jpg))))))

(defn- ^async/Future download-image-bytes
  "Download an image from the internet"
  [url]
  (let [client (io/HttpClient.)
        ^io/HttpClientRequest request (await (.getUrl client (Uri/parse url)))
        response (await (.close request))]
    (foundation/consolidateHttpClientResponseBytes response)))

(defn- ^async/Future read-local-image-bytes
  "Read the bytes of a local image"
  [path]
  (.readAsBytes (io/File. path)))

(defn save-book-cover
  "Save cover to memory"
  [book]
  (when-not (or (nil? (:cover-uri book))
                (empty? (:cover-uri book)))
    (let [image-dest (cover-path (:id book))
          bytes (await
                 (if (:local-cover? book)
                   ;; local image
                   (read-local-image-bytes (:cover-uri book))
                   ;; remote image
                   (download-image-bytes (:cover-uri book))))]
      (await (resize-and-save-image bytes image-dest)))))

