(ns paginae.image.utils
  {:no-dynamic true}
  (:require ["package:path_provider/path_provider.dart" :as path-provider]
            ["package:path/path.dart" :as path]
            ["package:image/image.dart" :as img]
            ["dart:io" :as io]
            ["package:flutter/foundation.dart" :as foundation]
            ["dart:async" :as async]))

(defonce image-directory-path (atom nil))

(defn init-image-directory
  "Set the image directory path"
  []
  (let [^io/Directory dir (await (path-provider/getApplicationDocumentsDirectory))]
    (reset! image-directory-path (.-path dir))))

(defn cover-path
  "Return the cover image path based on the id"
  [id]
  (path/join @image-directory-path (str id ".jpg")))

(def IMAGE-MAX-WIDTH
  "Maximum width in pixels for a saved image"
  300)

(defn resize-and-save-image-worker
  "Runs in a background isolate."
  [args]
  (let [input-bytes  (:input-bytes args)
        output-path  (:output-path args)]
    (when-let [decoded (img/decodeImage input-bytes)]
      (let [resized (img/copyResize decoded
                                    .width IMAGE-MAX-WIDTH)
            encoded (img/encodeJpg resized)]
        (await
         (.writeAsBytes (io/File. output-path) encoded)))
      true)))

(defn resize-and-save-image
  [input-bytes
   output-path]
  (await
   (foundation/compute
    resize-and-save-image-worker
    {:input-bytes input-bytes
     :output-path output-path})))

(defn- ^async/Future download-image-bytes
  [url]
  (let [client (io/HttpClient.)]
    (try
      (let [^io/HttpClientRequest request
            (await (.getUrl client (Uri/parse url)))
            response (await (.close request))]
        (await (foundation/consolidateHttpClientResponseBytes response)))
      (finally
        (.close client)))))

(defn- ^async/Future read-local-image-bytes
  "Read the bytes of a local image"
  [path]
  (.readAsBytes (io/File. path)))

(defn save-book-cover
  "Save cover to memory"
  [book]
  (when (seq (:cover-uri book))
    (let [image-dest (cover-path (:id book))
          bytes (await
                 (if (:local-cover? book)
                   ;; local image
                   (read-local-image-bytes (:cover-uri book))
                   ;; remote image
                   (download-image-bytes (:cover-uri book))))]
      (await (resize-and-save-image bytes image-dest)))))

