(ns paginae.add-book.add-book
  (:require [cljd.flutter :as flutter]
            ["package:flutter/material.dart" :as material]
            [paginae.image.utils :as img-utils]
            [paginae.image.widget :as image]
            [paginae.database :as db]
            [paginae.add-book.reading-status :as reading-status]
            [paginae.add-book.book-format :as book-format]
            [paginae.add-book.book-form :as book-form]
            ["../l10n/app_localizations.dart" :as app-l10n]
            ["package:image_picker/image_picker.dart" :as image-picker]
            [paginae.types.book :as book-type]
            ["package:flutter/widgets.dart" :as widgets]))

(defn- add-cover
  "Pick an image to use as cover"
  []

  (let [picker (image-picker/ImagePicker.)
        ^image-picker/XFile? picked-file (await (.pickImage picker
                                                            .source image-picker/ImageSource.gallery
                                                            .maxWidth 800
                                                            .maxHeight 800
                                                            .imageQuality 85))]
    (when picked-file
      (.-path picked-file))))

(defn- ^material/PreferredSizeWidget app-bar
  "App bar"
  [context
   {:keys [on-cancel
           on-save]}]

  (let [locales (app-l10n/AppLocalizations.of context)
        colorScheme (.-colorScheme (material/Theme.of context))]

    (material/AppBar
     .centerTitle true

     .leading
     (material/IconButton
      .icon
      (material/Icon material/Icons.close)
      .onPressed on-cancel
      .tooltip (.-cancel locales))

     .actions
     [(material/FilledButton
       .onPressed
       on-save

       .child
       (material/Text
        (.-save locales)

        .style
        (material/TextStyle
         .fontSize 16
         .color (.-onSurface colorScheme)))

       .style
       (material/ButtonStyle
        .backgroundColor
        (material/WidgetStatePropertyAll
         (.-surface colorScheme))

        .foregroundColor
        (material/WidgetStatePropertyAll
         (.-onBackground colorScheme))

        .padding
        (material/WidgetStatePropertyAll
         (material/EdgeInsets.all 15))))])))

(defn add-book-widget
  "Body widget on the add book screen"
  [{:keys [book-atom
           title-controller
           author-controller
           pages-controller]}]

  (flutter/widget
   :get {{{:flds [background]} .-colorScheme
          {:flds [headlineSmall]} .-textTheme} material/Theme}
   :context context
   :managed []
   :let [locales (app-l10n/AppLocalizations.of context)]

   (material/Container
    .margin
    (material/EdgeInsets.symmetric .horizontal 12 .vertical 0)

    .decoration
    (material/BoxDecoration
     .color background))

   (material/Center)

   (material/SingleChildScrollView)

   (material/Column
    .crossAxisAlignment
    material/CrossAxisAlignment.center

    .spacing 20)

   .children
   [;; Title
    (material/Text
     (.-addToLibrary locales)

     .style
     (.copyWith
      headlineSmall

      .fontWeight
      material/FontWeight.bold)

     .textAlign
     material/TextAlign.center)

    ;; Cover image
    (image/cover-image
     {:book @book-atom
      :placeholder-text (.-addCover (app-l10n/AppLocalizations.of context))
      :bordered? true
      :clickable? true
      :on-click (fn []
                  (let [cover (await (add-cover))]
                    (swap! book-atom book-type/update-local-cover cover)))})

    ;; Form
    (book-form/form-card title-controller author-controller pages-controller)

    ;; Reading status
    (reading-status/status-card book-atom)

    ;; Book formats
    (book-format/format-card book-atom)]))

(defn- show-snackbar
  "Show a snackbar in the given context with the given message"
  [context
   message]
  (-> (material/ScaffoldMessenger.of context)
      (.showSnackBar
       (material/SnackBar
        .content (material/Text message))))
  nil)

(defn- save-book
  "Validate and save book to database"
  [{:keys [context
           book-atom
           ^material/TextEditingController title-controller
           ^material/TextEditingController author-controller
           ^material/TextEditingController pages-controller
           go-to-my-books
           ^widgets/NavigatorState navigator]}]
  (let [new-title (.trim (.-text title-controller))
        new-author (.trim (.-text author-controller))
        empty-title? (not (seq new-title))
        empty-author? (not (seq new-author))
        locales (app-l10n/AppLocalizations.of context)]
    (cond
      empty-title?  (show-snackbar context (.-titleRequired locales))
      empty-author?  (show-snackbar context (.-authorRequired locales))
      :else (do
              (swap! book-atom #(assoc % :title new-title
                                       :author new-author
                                       :pages (parse-long (.trim (.-text pages-controller)))))
              (await (db/insert-book @book-atom))
              (await (img-utils/save-book-cover @book-atom))
              (go-to-my-books)
              (.pop navigator)))))

(defn add-book-screen
  [^book-type/Book book
   go-to-my-books]

  (flutter/widget
   :watch [_book-val (atom book) :as book-atom]
   :managed [title-controller (material/TextEditingController
                               .text (:title book))
             author-controller (material/TextEditingController
                                .text (:author @book-atom))

             pages-controller (material/TextEditingController
                               .text (str (:pages @book-atom)))]
   :get [material/Navigator]
   :context context

   (material/Scaffold
    .appBar
    (app-bar context {:on-cancel #(.pop navigator)
                      :on-save (fn []
                                 (save-book {:context context
                                             :book-atom book-atom
                                             :title-controller title-controller
                                             :author-controller author-controller
                                             :pages-controller pages-controller
                                             :go-to-my-books go-to-my-books
                                             :navigator navigator}))})

    .body
    (add-book-widget {:book-atom book-atom
                      :title-controller title-controller
                      :author-controller author-controller
                      :pages-controller pages-controller}))))
