(ns paginae.add-book.reading-status
  {:no-dynamic true}
  (:require ["../l10n/app_localizations.dart" :as app-l10n]
            ["package:flutter/material.dart" :as material]
            ["package:material_symbols_icons/symbols.dart" :as symbols]
            [cljd.flutter :as flutter]
            [paginae.types.book :as book]))

(defn- selection-circle
  "Circle to show when element is selected"
  [selected?]

  (flutter/widget
   :get {{{:flds [primary surface onSurface]} .-colorScheme} material/Theme}

   ;; Outer circle is painted `primary`
   (material/Container
    .width 20

    .height 20

    .decoration
    (material/BoxDecoration
     .shape
     material/BoxShape.circle

     .border
     (material/Border.all
      .color
      (if selected?
        primary
        (.withOpacity onSurface 0.3))

      .width 2)

     .color (if selected?
              primary
              material/Colors.transparent))

    .child
    (material/Center

     ;; Inner circle is painted `surface`
     .child
     (material/Container
      .height 8

      .width 8

      .decoration
      (material/BoxDecoration
       .shape
       material/BoxShape.circle

       .color (if selected?
                surface
                material/Colors.transparent)))))))

(defn- status-option
  "Radio-button-style status element"
  [{:keys [label icon color selected? on-tap]}]

  (flutter/widget
   :get {{{:flds [surface onSurface]} .-colorScheme} material/Theme}

   (material/InkWell
    .onTap on-tap

    .child
    (material/Container
     .padding
     (material/EdgeInsets.symmetric
      .horizontal 16
      .vertical 14)

     .decoration
     (material/BoxDecoration
      .color
      surface

      .borderRadius
      (material/BorderRadius.circular 12))

     .child
     (material/Row
      .spacing 12
      
      .children
      [(selection-circle selected?)

       ;; icon
       (material/Icon
        icon
        .color color
        .size 24
        .fill 1.0)

       ;; label
       (material/Text
        label

        .style
        (material/TextStyle
         .fontSize 16
         .color onSurface))])))))

(defn status-card
  "Card that holds all possible statuses"
  [book-atom]

  (flutter/widget
   :get {{{:flds [primary secondary tertiary background]} .-colorScheme} material/Theme
         {{:flds [bodyLarge]} .-textTheme} material/Theme}
   :context context
   :let [locales (app-l10n/AppLocalizations.of context)]

   (material/Card
    .color
    background

    .child
    (material/Container
     .padding
     (material/EdgeInsets.all 24)

     .child
     (material/Column
      .spacing 8

      .crossAxisAlignment
      material/CrossAxisAlignment.start

      .children
      [(material/Text
        (.-currentStatus locales)
        .style (.copyWith bodyLarge
                          .fontWeight material/FontWeight.bold))

       (status-option
        {:label (.-toRead locales)
         :icon symbols/Symbols.bookmark
         :color primary
         :selected? (= (:status @book-atom) :to-read)
         :on-tap #(swap! book-atom book/update-status :to-read)})

       (status-option
        {:label (.-currentlyReading locales)
         :icon symbols/Symbols.book_ribbon
         :color secondary
         :selected? (= (:status @book-atom) :reading)
         :on-tap #(swap! book-atom book/update-status :reading)})

       (status-option
        {:label (.-completed locales)
         :icon symbols/Symbols.check_circle
         :color tertiary
         :selected? (= (:status @book-atom) :done)
         :on-tap #(swap! book-atom book/update-status :done)})])))))