(ns paginae.database
  (:require [paginae.types.book :as book]
            [clojure.string :as str]
            ["dart:async" :as async]
            ["package:sqflite/sqflite.dart" :as sqlite]
            ["package:flutter/services.dart" :as services]
            ["package:path/path.dart" :as path]))

(defn run-schema [^sqlite/Database db sql]
  (doseq [stmt (remove str/blank?
                       (str/split sql #";"))]
    (.execute db stmt)))

(defn ^async/Future load-schema []
  (.loadString services/rootBundle "assets/sql/schema.sql"))

(defn ^async/Future init-db
  "Initialize the database"
  []
  (->
   (sqlite/getDatabasesPath)
   (.then
    (fn [db-path]
      (let [path (path/join db-path "paginae.db")]
        (sqlite/openDatabase
         path
         .version 1
         .onCreate
         (fn [^sqlite/Database db _version]
           (->
            (load-schema)
            (.then
             (fn [^String sql]
               (run-schema db sql)))))))))))

(defonce ^async/Future db-instance
  (delay (init-db)))

(defn ^async/Future get-db
  "Return the database instance, if not initialized, initialize it first"
  []
  (force db-instance))

(defn insert-book
  "Insert a book into the database"
  [^book/Book book]
  (->
   (get-db)
   (.then
    (fn [^sqlite/Database db]
      (.insert db
               "books"
               (book/to-db-map book))))))

(defn get-all-books
  "Query all books"
  []
  (->
   (get-db)
   (.then
    (fn [^sqlite/Database db]
      (.then
       (.query db "books")
       (fn [rows]
         (map book/from-db-entry rows)))))))

(defn get-reading-books
  "Query reading books"
  []
  (->
   (get-db)
   (.then
    (fn [^sqlite/Database db]
      (->
       (.query db
               "books"
               .where "status = \"reading\"")
       (.then
        #(map book/from-db-entry %)))))))

(defn get-book-counts
  "Query the book counts by status"
  []
  (->
   (get-db)
   (.then
    (fn [^sqlite/Database db]
        (->
         (.rawQuery db
                    "SELECT status, COUNT(*) as count
                       FROM books
                       GROUP BY status")
         (.then
          (fn [data]
            (->>
             data
             (map #(into {} %))
             (map (fn [row]
                    [(keyword (get row "status")) (get row "count")]))
             (into {})
             (merge
              {:to-read 0
               :reading 0
               :done 0})))))))))

(defn get-recent-activity
  "Query the last n activity items"
  [n]
  (->
   (get-db)
   (.then
    (fn [^sqlite/Database db]
      (.then
       (.query db
               "activity"
               .orderBy "date"
               .limit n)
       (fn [result]
         result))))))

(defn get-book [id]
  "Query for a book by id"
  (->
   (get-db)
   (.then
    (fn [^sqlite/Database db]
      (->
       (.query db
               "books"
               .where "id = ?"
               .whereArgs [id]
               .limit 1)
       (.then
        (fn [rows]
          (when (> (count rows) 0)
            (book/from-db-entry (first rows))))))))))
