(ns paginae.main
  {:no-dynamic true}
  (:require [cljd.flutter :as flutter]
            ["package:flutter/material.dart" :as material]
            [paginae.theme :as theme]
            [paginae.book-search.book-search :as book-search]
            [paginae.home.home :as home]
            [paginae.my-books.my-books :as my-books]
            [paginae.journal.journal :as journal]
            [paginae.image.utils :as img-utils]
            ["package:cljd_paginae/l10n/app_localizations.dart" :as app-l10n]
            ["package:material_symbols_icons/symbols.dart" :as symbols]))

(defn bottom-sheet-btn
  "Icon button for the bottom sheet"
  [{:keys [title
           icon
           active?
           on-pressed]}]

  (flutter/widget
   :get {{{:flds [onSurface primary onPrimary]} .-colorScheme} material/Theme
         {{:flds [labelMedium]} .-textTheme} material/Theme}

   (material/Expanded)

   .child
   (material/InkWell
    .onTap
    on-pressed

    .borderRadius
    (material/BorderRadius.circular 25.0))

   .child
   (material/Container
    .margin
    (material/EdgeInsets.all 5)

    .padding
    (material/EdgeInsets.all 2.5)

    .decoration
    (material/BoxDecoration
     .color (when active? primary)
     .borderRadius (material/BorderRadius.circular 20.0)))

   .child
   (material/Column

    .mainAxisSize
    material/MainAxisSize.min

    .mainAxisAlignment
    material/MainAxisAlignment.center)

   .children
   [(material/Icon
     icon

     .color
     (if active?
       onPrimary
       onSurface))

    (material/Text
     (.toUpperCase ^String title)

     .style
     (.copyWith
      labelMedium

      .color (if active?
               onPrimary
               onSurface)))]))

(defn bottom-sheet
  "Bottom navigation bar"
  [current-tab
   change-tab]

  (flutter/widget
   :get {{{:flds [surface]} .-colorScheme} material/Theme}
   :context context
   :let [locales (app-l10n/AppLocalizations.of context)]

   (material/SafeArea
    .child
    (material/Container
     .color
     surface

     .padding
     (material/EdgeInsets.only .top 10.0)

     .child
     (material/Row
      .mainAxisAlignment
      material/MainAxisAlignment.spaceAround

      .children
      [(bottom-sheet-btn
        {:title (.-bottomHome locales)
         :icon symbols/Symbols.home
         :active? (= :home current-tab)
         :on-pressed #(change-tab :home)})

       (bottom-sheet-btn
        {:title (.-bottomJournal locales)
         :icon symbols/Symbols.book_ribbon
         :active? (= :journal current-tab)
         :on-pressed #(change-tab :journal)})

       (bottom-sheet-btn
        {:title (.-bottomLibrary locales)
         :icon symbols/Symbols.library_books
         :active? (= :my-books current-tab)
         :on-pressed #(change-tab :my-books)})

       (bottom-sheet-btn
        {:title (.-bottomAdd locales)
         :icon symbols/Symbols.add
         :active? (= :search current-tab)
         :on-pressed #(change-tab :search)})])))))

(defn main-screen
  []

  (flutter/widget
   :watch [tab (atom :home) :as current-tab
           books-filter (atom nil) :as filter-atom]

   (material/MaterialApp
    .title
    "Paginae"

    .localizationsDelegates
    app-l10n/AppLocalizations.localizationsDelegates

    .supportedLocales
    app-l10n/AppLocalizations.supportedLocales

    .theme
    theme/light-theme

    .darkTheme
    theme/dark-theme

    .themeMode
    material/ThemeMode.dark

    .home
    (material/Scaffold

     .body
     (material/Container

      .margin
      (material/EdgeInsets.only
       .top 10
       .left 20
       .right 20)

      .child
      (case tab
        :home (home/home-widget
               {:go-to-add #(reset! current-tab :search)
                :go-to-journal #(reset! current-tab :journal)
                :go-to-reading-shelf (fn []
                                       (reset! filter-atom :reading)
                                       (reset! current-tab :my-books))
                :go-to-to-read-shelf (fn []
                                       (reset! filter-atom :to-read)
                                       (reset! current-tab :my-books))
                :go-to-done-shelf (fn []
                                    (reset! filter-atom :done)
                                    (reset! current-tab :my-books))
                :go-to-favorite-shelf (fn []
                                        (reset! filter-atom :favorite)
                                        (reset! current-tab :my-books))})

        :journal (journal/journal-widget)

        :my-books (my-books/my-books-widget books-filter)

        :search (book-search/book-search-widget
                 {:go-to-my-books (fn []
                                    (reset! filter-atom nil)
                                    (reset! current-tab :my-books))
                  :on-image-saved (fn []
                                    (swap! my-books/refresh-atom inc))})))

     .bottomNavigationBar
     (bottom-sheet
      tab
      (fn [new-tab]
        (when (= new-tab :my-books)
          (reset! filter-atom nil))

        (reset! current-tab new-tab)))))))

(defn main
  []
  (await (img-utils/init-image-directory))

  (flutter/run
   (main-screen)))
