(ns paginae.main
  {:no-dynamic true}
  (:require [cljd.flutter :as flutter]
            ["package:flutter/material.dart" :as material]
            [paginae.theme :as theme]
            [paginae.book-search.book-search :as book-search]
            [paginae.home.home :as home]
            [paginae.my-books.my-books :as my-books]
            [paginae.journal.journal :as journal]
            [paginae.image.utils :as img-utils]
            ["../l10n/app_localizations.dart" :as app-l10n]
            ["package:material_symbols_icons/symbols.dart" :as symbols]))

(defn bottom-sheet-btn
  "Icon button for the bottom sheet"
  [{:keys [title
           icon
           active?
           on-pressed]}]

  (flutter/widget
   :get {{{:flds [onSurface primary onPrimary]} .-colorScheme} material/Theme
         {{:flds [labelMedium]} .-textTheme} material/Theme}

   (material/Expanded)

   .child
   (material/InkWell
    .onTap
    on-pressed

    .borderRadius
    (material/BorderRadius.circular 25.0))

   .child
   (material/Container
    .margin
    (material/EdgeInsets.all 5)

    .padding
    (material/EdgeInsets.all 2.5)

    .decoration
    (material/BoxDecoration
     .color (when active? primary)
     .borderRadius (material/BorderRadius.circular 20.0)))

   .child
   (material/Column

    .mainAxisSize
    material/MainAxisSize.min

    .mainAxisAlignment
    material/MainAxisAlignment.center)

   .children
   [(material/Icon
     icon

     .color
     (if active?
       onPrimary
       onSurface))

    (material/Text
     (.toUpperCase ^String title)

     .style
     (.copyWith
      labelMedium

      .color (if active?
               onPrimary
               onSurface)))]))

(defn bottom-sheet
  "Bottom navigation bar"
  [current-tab
   change-tab]

  (flutter/widget
   :get {{{:flds [surface]} .-colorScheme} material/Theme}
   :context context
   :let [locales (app-l10n/AppLocalizations.of context)]

   (material/SafeArea
    .child
    (material/Container
     .color
     surface

     .padding
     (material/EdgeInsets.only .top 10.0)

     .child
     (material/Row
      .mainAxisAlignment
      material/MainAxisAlignment.spaceAround

      .children
      [(bottom-sheet-btn
        {:title (.-bottomHome locales)
         :icon symbols/Symbols.home
         :active? (= 0 current-tab)
         :on-pressed #(change-tab 0)})

       (bottom-sheet-btn
        {:title (.-bottomJournal locales)
         :icon symbols/Symbols.book_ribbon
         :active? (= 1 current-tab)
         :on-pressed #(change-tab 1)})

       (bottom-sheet-btn
        {:title (.-bottomLibrary locales)
         :icon symbols/Symbols.library_books
         :active? (= 2 current-tab)
         :on-pressed #(change-tab 2)})

       (bottom-sheet-btn
        {:title (.-bottomAdd locales)
         :icon symbols/Symbols.add
         :active? (= 3 current-tab)
         :on-pressed #(change-tab 3)})])))))

(defn main-screen
  []

  (flutter/widget
   :watch [tab (atom 0) :as current-tab
           books-filter (atom nil) :as filter-atom]

   (material/MaterialApp
    .title
    "Paginae"

    .localizationsDelegates
    app-l10n/AppLocalizations.localizationsDelegates

    .supportedLocales
    app-l10n/AppLocalizations.supportedLocales

    .theme
    theme/light-theme

    .darkTheme
    theme/dark-theme

    .themeMode
    material/ThemeMode.dark

    .home
    (material/Scaffold

     .body
     (material/Container

      .margin
      (material/EdgeInsets.only
       .top 10

       .left 20

       .right 20)

      .child
      (case tab
        0 (home/home-widget
           {:go-to-add #(reset! current-tab 3)
            :go-to-journal #(reset! current-tab 1)
            :go-to-reading-shelf (fn []
                                   (reset! filter-atom :reading)
                                   (reset! current-tab 2))
            :go-to-to-read-shelf (fn []
                                   (reset! filter-atom :to-read)
                                   (reset! current-tab 2))
            :go-to-done-shelf (fn []
                                (reset! filter-atom :done)
                                (reset! current-tab 2))
            :go-to-favorite-shelf (fn []
                                    (reset! filter-atom :favorite)
                                    (reset! current-tab 2))})

        1 (journal/journal-widget)

        2 (my-books/my-books-widget books-filter)

        3 (book-search/book-search-widget
           {:go-to-my-books (fn []
                              (reset! filter-atom nil)
                              (reset! current-tab 2))
            :on-image-saved (fn []
                              (swap! my-books/refresh-atom inc))})))

     .bottomNavigationBar
     (bottom-sheet
      tab
      (fn [i]
        (when (= i 2)
          (reset! filter-atom nil))

        (reset! current-tab i)))))))

(defn main
  []
  (await (img-utils/init-image-directory))

  (flutter/run
   (main-screen)))
