(ns paginae.theme
  {:no-dynamic true}
  (:require ["package:flutter/material.dart" :as material]))

(defonce serif-font
  "NotoSerif")

(defonce sans-serif-font
  "Manrope")

(def primary
  "Material palette based on #8A9A5B as primary color"
  {:0   (material/Color 0xFF000000)
   :10  (material/Color 0xFF1C2110)
   :20  (material/Color 0xFF323A1F)
   :30  (material/Color 0xFF49532E)
   :40  (material/Color 0xFF606C3D)
   :50  (material/Color 0xFF78864E)
   :60  (material/Color 0xFF91A063)
   :70  (material/Color 0xFFAAB978)
   :80  (material/Color 0xFFC4D38F)
   :90  (material/Color 0xFFDFEEA8)
   :95  (material/Color 0xFFEEF8C8)
   :99  (material/Color 0xFFFBFFE8)
   :100 (material/Color 0xFFFFFFFF)})

(def secondary
  "Material palette based on #B35A44 as secondary color"
  {:0   (material/Color 0xFF000000)
   :10  (material/Color 0xFF2A120E)
   :20  (material/Color 0xFF4A231C)
   :30  (material/Color 0xFF6A3429)
   :40  (material/Color 0xFF8A4637)
   :50  (material/Color 0xFFA35A49)
   :60  (material/Color 0xFFBD6F5C)
   :70  (material/Color 0xFFD78470)
   :80  (material/Color 0xFFF19A86)
   :90  (material/Color 0xFFFFDAD2)
   :95  (material/Color 0xFFFFECE8)
   :99  (material/Color 0xFFFFFBFA)
   :100 (material/Color 0xFFFFFFFF)})

(def tertiary
  "Material palette based on #B384B1 as tertiary color"
  {:0   (material/Color 0xFF000000)
   :10  (material/Color 0xFF241A25)
   :20  (material/Color 0xFF3D2F3F)
   :30  (material/Color 0xFF564558)
   :40  (material/Color 0xFF705C72)
   :50  (material/Color 0xFF89738C)
   :60  (material/Color 0xFFA38AA7)
   :70  (material/Color 0xFFBDA2C2)
   :80  (material/Color 0xFFD9BADF)
   :90  (material/Color 0xFFF5D8FA)
   :95  (material/Color 0xFFFDEBFF)
   :99  (material/Color 0xFFFFFBFF)
   :100 (material/Color 0xFFFFFFFF)})

(def neutral
  "Material palette based on #F5F2ED as tertiary color"
  {:0   (material/Color 0xFF000000)
   :10  (material/Color 0xFF1F1F1E)
   :20  (material/Color 0xFF343433)
   :30  (material/Color 0xFF4A4A49)
   :40  (material/Color 0xFF61615F)
   :50  (material/Color 0xFF797977)
   :60  (material/Color 0xFF93918F)
   :70  (material/Color 0xFFADABA9)
   :80  (material/Color 0xFFC9C6C2)
   :90  (material/Color 0xFFE5E1DC)
   :95  (material/Color 0xFFF5F2ED)
   :99  (material/Color 0xFFFFFBFF)
   :100 (material/Color 0xFFFFFFFF)})

(def text-theme
  "Material-style text theme"
  (material/TextTheme
   ;; DISPLAY (NotoSerif)
   .displayLarge
   (material/TextStyle
    .fontFamily serif-font
    .fontSize 96.0
    .fontWeight material/FontWeight.w300
    .letterSpacing -1.5)

   .displayMedium
   (material/TextStyle
    .fontFamily serif-font
    .fontSize 60.0
    .fontWeight material/FontWeight.w300
    .letterSpacing -0.5)

   .displaySmall
   (material/TextStyle
    .fontFamily serif-font
    .fontSize 48.0,
    .fontWeight material/FontWeight.w400
    .letterSpacing 0.0)

   ;; HEADLINES (NotoSerif)
   .headlineMedium
   (material/TextStyle
    .fontFamily serif-font
    .fontSize 34.0
    .fontWeight material/FontWeight.w400
    .letterSpacing 0.25)

   .headlineSmall
   (material/TextStyle
    .fontFamily serif-font
    .fontSize 24.0
    .fontWeight material/FontWeight.w400
    .letterSpacing 0.0)

   ;; TITLES (NotoSerif)
   .titleLarge
   (material/TextStyle
    .fontFamily serif-font
    .fontSize 20.0
    .fontWeight material/FontWeight.w500
    .letterSpacing 0.15)

   .titleMedium
   (material/TextStyle
    .fontFamily serif-font
    .fontSize 16.0
    .fontWeight material/FontWeight.w400
    .letterSpacing 0.15)

   .titleSmall
   (material/TextStyle
    .fontFamily serif-font
    .fontSize 14.0
    .fontWeight material/FontWeight.w500
    .letterSpacing 0.1)

   ;; BODY (Manrope)
   .bodyLarge
   (material/TextStyle
    .fontFamily sans-serif-font
    .fontSize 16.0
    .fontWeight material/FontWeight.w400
    .letterSpacing 0.5)

   .bodyMedium
   (material/TextStyle
    .fontFamily sans-serif-font
    .fontSize 14.0
    .fontWeight material/FontWeight.w400
    .letterSpacing 0.25)

   .bodySmall
   (material/TextStyle
    .fontFamily sans-serif-font
    .fontSize 12.0
    .fontWeight material/FontWeight.w400
    .letterSpacing 0.4)

   ;; LABELS (Manrope)
   .labelLarge
   (material/TextStyle
    .fontFamily sans-serif-font
    .fontSize 14.0
    .fontWeight material/FontWeight.w500
    .letterSpacing 1.25)

   .labelSmall
   (material/TextStyle
    .fontFamily sans-serif-font
    .fontSize 10.0
    .fontWeight material/FontWeight.w400
    .letterSpacing 1.5)))

(defn card-theme
  "Theme for the card"
  [{:keys [color]}]
  (material/CardThemeData
   .color color

   .elevation 2.0

   .shape
   (material/RoundedRectangleBorder
    .borderRadius (material/BorderRadius.circular 20.0))))

(defn list-tile-theme
  "Theme for a list tile"
  [{:keys [color]}]
  (material/ListTileThemeData
   .tileColor color

   .shape
   (material/RoundedRectangleBorder
    .borderRadius
    (material/BorderRadius.circular 16.0))))

(defn app-bar-theme
  "Theme for the app bar"
  [{:keys [background
           foreground]}]
  (material/AppBarTheme
   .backgroundColor background

   .foregroundColor foreground

   .elevation 0))

(defn filled-button-theme
  "Theme for filled buttons"
  [{:keys [background
           foreground]}]
  (material/FilledButtonThemeData
   .style
   (material/ButtonStyle
    .backgroundColor
    (material/WidgetStatePropertyAll
     ^material/Color background)

    .foregroundColor
    (material/WidgetStatePropertyAll
     ^material/Color foreground)

    .shape
    (material/WidgetStatePropertyAll
     (material/RoundedRectangleBorder
      .borderRadius
      (material/BorderRadius.circular 16.0))))))

(defn bottom-navigation-theme
  "Theme for the bottom navigation bar"
  [{:keys [background selected unselected]}]
  (material/BottomNavigationBarThemeData
   .backgroundColor background

   .selectedItemColor selected

   .unselectedItemColor unselected))

(defn dialog-theme
  "Theme for dialogs"
  [{:keys [background]}]
  (material/DialogThemeData

   .backgroundColor background

   .shape
   (material/RoundedRectangleBorder
    .borderRadius
    (material/BorderRadius.circular 20.0))))

(defn theme
  "Generate a theme based on the given color scheme and shadow color"
  [^material/ColorScheme color-scheme
   shadow-color]
  (material/ThemeData
   .useMaterial3
   true

   .colorScheme
   color-scheme

   ;; BACKGROUND
   .scaffoldBackgroundColor
   (.-background color-scheme)

   .canvasColor
   (.-surface color-scheme)

   ;; TYPOGRAPHY
   .fontFamily
   sans-serif-font

   .textTheme
   text-theme

   ;; CARD
   .cardTheme
   (material/CardThemeData
    .color
    (.-surface color-scheme)

    .shadowColor
    shadow-color

    .elevation
    2.0

    .shape
    (material/RoundedRectangleBorder
     .borderRadius
     (material/BorderRadius.circular 20.0)))

   ;; LIST TILES
   .listTileTheme
   (list-tile-theme
    {:color (.-surface color-scheme)})

   ;; APP BAR
   .appBarTheme
   (app-bar-theme
    {:background (.-background color-scheme)
     :foreground (.-onBackground color-scheme)})

   ;; BUTTONS
   .filledButtonTheme
   (filled-button-theme
    {:background (.-primary color-scheme)
     :foreground (.-onPrimary color-scheme)})

   ;; BOTTOM NAV
   .bottomNavigationBarTheme
   (bottom-navigation-theme
    {:background (.-surface color-scheme)
     :selected (.-primary color-scheme)
     :unselected (.-onSurfaceVariant color-scheme)})

   ;; DIALOGS
   .dialogTheme
   (dialog-theme
    {:background (.-surface color-scheme)})

   ;; DIVIDERS and BORDERS
   .dividerColor
   (.-outline color-scheme)))


(def light-theme
  "Light theme"
  (theme
   (material/ColorScheme
    .brightness material/Brightness.light
    .primary (material/Color 0xFF8A9A5B)
    .onPrimary (material/Color 0xFFFFFFFF)

    .secondary (material/Color 0xFFB35A44)
    .onSecondary (material/Color 0xFFFFFFFF)

    .tertiary (material/Color 0xFFB384B1)
    .onTertiary (material/Color 0xFFFFFFFF)

    .surface (:90 neutral)
    .onSurface (material/Color 0xFF2B2B2B)

    .background (material/Color 0xFFF5F2ED)
    .onBackground (material/Color 0xFF2B2B2B)

    .surfaceVariant (material/Color 0xFFEAE6E0)
    .onSurfaceVariant (material/Color 0xFF5A5A5A)

    .outline (material/Color 0xFFD0CBC5)

    .error (material/Color 0xFFB00020)
    .onError (material/Color 0xFFFFFFFF))

   (material/Color 0x1A000000)))

(def dark-theme
  "Dark theme"
  (theme
   (material/ColorScheme
    .brightness material/Brightness.dark

    .primary (material/Color 0xFFA3B86C)
    .onPrimary (material/Color 0xFF1E1E1E)

    .secondary (material/Color 0xFFD07A63)
    .onSecondary (material/Color 0xFF1E1E1E)

    .tertiary (material/Color 0xFFC59BC2)
    .onTertiary (material/Color 0xFF1E1E1E)

    .surface (:20 neutral)
    .onSurface (material/Color 0xFFEAEAEA)

    .background (material/Color 0xFF1E1E1E)
    .onBackground (material/Color 0xFFEAEAEA)

    .surfaceVariant (material/Color 0xFF2A2A2A)
    .onSurfaceVariant (material/Color 0xFFBDBDBD)

    .outline (material/Color 0xFF444444)

    .error (material/Color 0xFFCF6679)
    .onError (material/Color 0xFF000000))

   (material/Color 0x1AFFFFFF)))
