(ns paginae.book-search.book-search
  {:no-dynamic true}
  (:require ["package:cljd_paginae/l10n/app_localizations.dart" :as app-l10n]
            ["package:flutter/animation.dart" :as animation]
            ["package:flutter/material.dart" :as material]
            ["package:material_symbols_icons/symbols.dart" :as symbols]
            [cljd.flutter :as flutter]
            [paginae.book-search.barcode-scanner :as barcode-scanner]
            [paginae.book-search.book-list :as book-list]
            [paginae.book-search.query :as query]
            [paginae.book-search.search-widget :as search-widget]))

(defn- load-books
  "Function to load more books"
  [{:keys [query
           loading-more
           unknown-str
           no-response-str
           books-atom
           total-atom
           offset-atom
           has-more
           error-atom]}]
  (when (not @loading-more)
    (reset! loading-more true)

    (let [result (await (query/query-books query @offset-atom unknown-str no-response-str))]
      (when-not (:error result)
        (swap! books-atom into (:data result))
        (reset! total-atom (:total result))
        (swap! offset-atom + 20)
        (reset! has-more (not= (:total result) (count @books-atom))))
      (reset! loading-more false)
      (reset! error-atom (:error result)))))

(defn- go-up-fab
  "Floating action button to go to the top of the screen"
  [show-fab
   on-pressed]
  (flutter/widget
   :watch [show-fab? show-fab]
   :when show-fab?
   (material/FloatingActionButton
    .child
    (material/Icon symbols/Symbols.keyboard_double_arrow_up)

    .onPressed
    on-pressed)))

(defn book-search-widget
  "Widget for the add book screen. It allows to search for a book, scan its barcode or go to a manual entry"
  [{:keys [go-to-my-books]}]
  (flutter/widget
   :get {{{:flds [background]} .-colorScheme
          {:flds [headlineSmall]} .-textTheme} material/Theme}

   :context context

   :watch [query (atom "") :as query-atom
           _offset (atom 0) :as offset-atom
           _books (atom []) :as books-atom
           _total-books (atom nil) :as total-atom
           scanning? (atom false) :as scanning
           _has-more? (atom true) :as has-more
           error (atom nil) :as error-atom
           _loading (atom false) :as loading-atom]

   :let [locales (app-l10n/AppLocalizations.of context)
         portrait? (= (.-orientation (material/MediaQuery.of context)) material/Orientation.portrait)]


   :managed [loading-more (atom false) :dispose nil
             show-fab (atom false) :dispose nil
             scroll-controller
             (let [controller (material/ScrollController)
                   locales (app-l10n/AppLocalizations.of context)
                   unknown-str (.-unknown locales)
                   no-response-str (.-noServerResponse locales)
                   handler (fn []
                             (let [offset (.-offset controller)
                                   position (.-position controller)]
                               (when (and
                                      @has-more
                                      (not @loading-more)
                                      (> (.-pixels position)
                                         (- (.-maxScrollExtent position) 500)))

                                 (load-books {:query @query-atom
                                              :loading-more loading-more
                                              :unknown-str unknown-str
                                              :no-response-str no-response-str
                                              :books-atom books-atom
                                              :total-atom total-atom
                                              :offset-atom offset-atom
                                              :has-more has-more
                                              :error-atom error-atom}))

                               (cond
                                 (and (> 300 offset) @show-fab)
                                 (reset! show-fab false)

                                 (and (<= 300 offset) (not @show-fab))
                                 (reset! show-fab true))))]
               (.addListener controller handler)
               controller)]



   (material/Scaffold
    .floatingActionButton
    (go-up-fab
     show-fab
     (fn []
       (-> scroll-controller
           (.animateTo
            0

            .duration (dart:core/Duration .milliseconds 400)

            .curve animation/Curves.easeInOut))
       ()))

    .body
    (material/Container

     .decoration
     (material/BoxDecoration
      .color background)

     .child
     (material/CustomScrollView
      .controller scroll-controller

      .slivers
      [;; App bar
       (material/SliverAppBar
        .pinned portrait?

        .floating true

        .flexibleSpace
        (material/Center
         .child
         (material/Text
          (.-searchTitle locales)

          .textAlign
          material/TextAlign.center

          .style
          (.copyWith
           headlineSmall

           .fontWeight
           material/FontWeight.bold))))

       ;; Either search or barcode scanner
       (material/SliverToBoxAdapter
        .child
        (if scanning?
          (barcode-scanner/barcode-scanner scanning
                                           query-atom)

          (search-widget/search-widget {:on-submitted (fn [text]
                                                        (let [locales (app-l10n/AppLocalizations.of context)]
                                                          (reset! loading-atom true)
                                                          (reset! query-atom text)
                                                          (reset! books-atom [])
                                                          (reset! offset-atom 0)
                                                          (reset! total-atom nil)
                                                          (reset! error-atom nil)
                                                          (load-books {:query text
                                                                       :loading-more loading-more
                                                                       :unknown-str (.-unknown locales)
                                                                       :no-response-str (.-noServerResponse locales)
                                                                       :books-atom books-atom
                                                                       :total-atom total-atom
                                                                       :offset-atom offset-atom
                                                                       :has-more has-more
                                                                       :error-atom error-atom})
                                                          (reset! loading-atom false)))
                                        :text @query-atom
                                        :scanning scanning
                                        :go-to-my-books go-to-my-books})))

       (if (and (not scanning?)
                (seq query))
         (book-list/book-list {:books @books-atom
                               :total-books @total-atom
                               :loading? (nil? @total-atom)
                               :as-list? portrait?
                               :loading-more loading-more
                               :go-to-my-books go-to-my-books
                               :error error})
         (material/SliverToBoxAdapter
          .child
          (material/Container)))])))))

