(ns paginae.book-search.book-list
  {:no-dynamic true}
  (:require ["package:cljd_paginae/l10n/app_localizations.dart" :as app-l10n]
            ["package:flutter/material.dart" :as material]
            [cljd.flutter :as flutter]
            [paginae.common.book-editor.book-editor :as book-editor]
            [paginae.database :as db]
            [paginae.image.widget :as image]
            [paginae.theme :as theme]
            [paginae.types.book-search-result :as book-search-result]
            [paginae.types.book :as book-type]))

(defn- book-card
  "Card that displays a result book after a search"
  [^book-search-result/BookSearchResult book
   go-to-my-books]

  (flutter/widget
   :get {{{:flds [titleLarge]} .-textTheme} material/Theme}
   :get [material/Navigator]
   :context context
   :let [locales (app-l10n/AppLocalizations.of context)]

   (material/InkWell
    .onTap (fn []
             (.push
              navigator
              (#/(material/MaterialPageRoute Object)
               .builder
               (flutter/build
                (book-editor/book-editor {:book (book-type/from-search-result book)
                                          :on-save (fn [book]
                                                     (db/insert-book book))
                                          :on-navigation go-to-my-books}))))
             nil)

    .child
    (material/Card
     .child
     (material/Container
      .padding (material/EdgeInsets.all 10)

      .child
      (material/Row
       .spacing 30

       .children
       [;; Book's cover
        (image/cover-image
         {:book book
          :placeholder-text (.-noCover locales)
          :bordered? false
          :clickable? false
          :on-click nil})

        (material/Expanded
         .child
         (material/Column
          .crossAxisAlignment material/CrossAxisAlignment.start

          .spacing 5

          .children
          [;; Book's title
           (material/Text
            (:title book)
            .style titleLarge
            .softWrap true)

           ;; Book's author
           (material/Text
            (.toUpperCase ^String (:author book))

            .style (material/TextStyle
                    .color (:60 theme/neutral)
                    .fontSize 16
                    .fontWeight material/FontWeight.bold))

           ;; Book's first publication year
           (material/Text
            ((.-firstPublished locales) (:first-published book))

            .style (material/TextStyle
                    .color (:50 theme/neutral)
                    .fontSize 14))]))]))))))

(defn book-list
  "List to display search book results"
  [{:keys [books
           total-books
           loading?
           as-list?
           loading-more
           go-to-my-books
           error]}]

  (flutter/widget
   :get {{{:flds [labelLarge]} .-textTheme} material/Theme
         {{:flds [onBackground]} .-colorScheme} material/Theme}
   :watch [_loading-more loading-more]
   :context context

   (cond
     error
     (material/SliverToBoxAdapter
      .child
      (material/Padding
       .padding
       (material/EdgeInsets.only .top 20)

       .child
       (material/Center
        .child
        (material/Text
         error

         .textAlign
         material/TextAlign.center

         .style
         (.copyWith
          labelLarge

          .color
          (.withOpacity onBackground 0.7)

          .letterSpacing
          2.0)))))


     ;; Results are loading
     loading?
     (material/SliverToBoxAdapter
      .child
      (material/Padding
       .padding
       (material/EdgeInsets.only .top 20)

       .child
       (material/Center
        .child
        (material/SizedBox
         .height 80

         .width 80

         .child
         (material/CircularProgressIndicator)))))

     ;; No results
     (= 0 total-books)
     (material/SliverToBoxAdapter
      .child
      (material/Padding
       .padding
       (material/EdgeInsets.only .top 20)

       .child
       (material/Center
        .child
        (material/Text
         (.-searchNoResults (app-l10n/AppLocalizations.of context))

         .textAlign
         material/TextAlign.center

         .style
         (.copyWith
          labelLarge

          .color
          (.withOpacity onBackground 0.7)

          .letterSpacing
          2.0)))))

     ;; Display results
     :else
     (let [item-count (if @loading-more
                        (inc (count books))
                        (count books))]

       (if as-list?
         (material/SliverList.builder
          .itemCount item-count

          .itemBuilder
          (fn [_context index]
            (if (and @loading-more
                     (= index (dec item-count)))

              (material/Padding
               .padding
               (material/EdgeInsets.symmetric .horizontal 0
                                              .vertical 20)

               .child
               (material/Center

                .child
                (material/SizedBox

                 .height 80

                 .width 80

                 .child
                 (material/CircularProgressIndicator))))

              (book-card (nth books index) go-to-my-books))))

         (material/SliverGrid.builder
          .itemCount item-count

          .gridDelegate
          (material/SliverGridDelegateWithFixedCrossAxisCount
           .crossAxisCount 2
           .crossAxisSpacing 10
           .mainAxisSpacing 5
           .childAspectRatio (/ 16 9))

          .itemBuilder
          (fn [_context index]
            (if (and @loading-more
                     (= index (dec item-count)))

              (material/Padding
               .padding
               (material/EdgeInsets.symmetric .horizontal 0
                                              .vertical 20)

               .child
               (material/LinearProgressIndicator))

              (book-card (nth books index) go-to-my-books)))))))))
