(ns paginae.book-search.query
  {:no-dynamic true}
  (:require [paginae.types.book :as book]
            [clojure.string :as str]
            ["package:http/http.dart" :as http]
            ["dart:convert" :as convert]))

(defrecord QueryResult
           [total ;; Number of results
            offset ;; Current offset
            data ;; Result data
            error])

(defn query-books
  "Query the Open Library to search for books"
  [query ;; Query to search
   offset ;; Offset of data to search
   unknown-str ;; String to use as placeholder when no data is provided
   no-response-str ;; String to return when no response
   ]

  (let [uri (Uri/https
             "openlibrary.org"
             "/search.json"
             {"q" (str "title: \"" query "\" OR author_name: \"" query "\" OR isbn: \"" query "\"")
              "fields" "author_name,title,cover_i,first_publish_year,key,cover_edition_key,number_of_pages_median"
              "limit" "20"
              "offset" (str offset)})]
    ;; TODO: Maybe add "author_key" to fields and query the author's API https://openlibrary.org/authors/{author_key}.json to get a more localized name


    (letfn [(handle-error [_error]
              (map->QueryResult
               {:total 0
                :offset 0
                :data []
                :error "Couldn't retrieve data from OpenLibrary. Please try again."}))

            (filter-fn [book]
              (let [title (get book "title")]
                (and
                 (contains? book "key")
                 (some? title)
                 (not (str/blank? title)))))

            (handle-response [^http/Response response]
              (if (= (.-statusCode response) 200)
                (let [json (convert/jsonDecode (.-body response))]
                  (map->QueryResult
                   {:total (get json "num_found")
                    :offset (get json "offset")
                    :data (map #(book/book-from-query-result % unknown-str)
                               (filter filter-fn
                                       (get json "docs" [])))}))
                (handle-error no-response-str)))]

      (-> (http/get uri)
          (.timeout (Duration .seconds 10))
          (.then handle-response)
          (.catchError (fn [error]
                         (dart:core/print (str "ERROR: " error))
                         ;; (handle-error error)
                         (map->QueryResult
                          {:total 0
                           :offset 0
                           :data []
                           :error "Couldn't retrieve data from OpenLibrary. Please try again."})))))))